SELECT CPH.PROVIDERID,
CPH.PROVIDERNAME,
CPH.REQUESTAMOUNT,
CPH.APPROVEDAMOUNT,
CPH.TREATMENTTYPE,
CPH.NOOFCLAIMS,
CPH.PROVIDERCODE,
ROUND((CPH.APPROVEDAMOUNT/CPH.NOOFCLAIMS),2) AVGPERCOST,
DECODE(LSTROPTION1, 'Y', 1, 0) ISSERIALNONEEDED
FROM (SELECT IMPRO.PROVIDERID,IMPRO.PROVIDERNAME,
SUM(HDR.REQUEST_AMOUNT) REQUESTAMOUNT,SUM(NVL(HDR.APPROVED_AMOUNT,0)) APPROVEDAMOUNT,
GEN5.CONSTANTNAME TREATMENTTYPE,COUNT(*) NOOFCLAIMS, IMPRO.PROVIDERCODE FROM IM_CLAIM_PROCESS_HEADER HDR
JOIN IM_PROVIDERS IMPRO ON IMPRO.PROVIDERCODE = HDR.PROVIDER_CODE 
LEFT JOIN GENCONSTANT GEN5 ON GEN5.CONSTANTVALUE=HDR.TREATMENT_TYPE AND GEN5.CATEGORY='APPLICABLE' AND UPPER(GEN5.LANGUAGECODE) = UPPER('EN-US')
WHERE HDR.LASTMODIFIEDON BETWEEN :SDATE AND :EDATE AND
HDR.TREATMENT_TYPE = Nvl(:TREATMENTTYPE,HDR.TREATMENT_TYPE) AND 
HDR.CLAIM_STATUS=2 AND HDR.PROVIDER_CODE = Nvl(:PROVIDERCODE,HDR.PROVIDER_CODE)   
GROUP BY IMPRO.PROVIDERID,IMPRO.PROVIDERNAME,GEN5.CONSTANTNAME,IMPRO.PROVIDERCODE) CPH
where
CPH.APPROVEDAMOUNT  >= :SNO and   CPH.APPROVEDAMOUNT<= decode(:ENO,0,CPH.APPROVEDAMOUNT,:ENO)


:SNO - starting amount
:ENO - end amount
:SDATE - Start DATE
:EDATE - End DATE

:PROVIDERCODE

SELECT PROVIDERCODE,PROVIDERID,PROVIDERNAME FROM IM_PROVIDERS

:TREATMENTTYPE

SELECT CONSTANTVALUE,CONSTANTNAME FROM GENCONSTANT WHERE CATEGORY = 'APPLICABLE' AND UPPER(LANGUAGECODE) = UPPER('EN-US')

