SELECT HNMREC.* FROM(SELECT IMPRO.PROVIDERID,IMPRO.PROVIDERNAME,
HDR.PROVIDER_CODE,IMVRDD.CODE DENIALCODE,IMVRDD.SHORTDESC DENIALREASON,
SUM(DTL.DENIAL_VALUE) RECOVERYAMOUNT,COUNT(*) NOOFCLAIMS, DECODE(1, 'Y', 1, 0) ISSERIALNONEEDED
FROM IM_CLAIM_PROCESS_HEADER HDR
JOIN IM_PROVIDERS IMPRO ON IMPRO.PROVIDERCODE = HDR.PROVIDER_CODE and
HDR.CLAIM_STATUS=2 and HDR.PROVIDER_CODE = Nvl(:PROVIDERCODE,HDR.PROVIDER_CODE) AND
HDR.LASTMODIFIEDON between :SDATE AND :EDATE
JOIN IM_CLAIM_PROCESS_DETAIL DTL ON DTL.CLAIM_CODE = HDR.CLAIM_CODE AND DTL.ACTIVITY_STATUS IN (2,3)
LEFT JOIN IM_VERSION_DETALIS IMVRDD ON (IMVRDD.DETAILCODE) = DTL.DENIAL_REASON
WHERE HDR.LASTMODIFIEDON BETWEEN :SDATE AND :EDATE and (select count(*) from IM_CLAIM_PROCESS_DETAIL_DTL SDTL where SDTL.ACTIVITY_DETAIL_CODE = DTL.ACTIVITY_DETAIL_CODE AND SDTL.DENIEDFOR = 2 )>0
GROUP BY IMPRO.PROVIDERID,IMPRO.PROVIDERNAME,HDR.PROVIDER_CODE,IMVRDD.CODE,IMVRDD.SHORTDESC) HNMREC
where round(HNMREC.RECOVERYAMOUNT) <>0


:PROVIDERCODE

SELECT PROVIDERCODE,PROVIDERID,PROVIDERNAME FROM IM_PROVIDERS