SELECT UTI.* FROM (SELECT
IMPRO.PROVIDERID,
IMPRO.PROVIDERNAME,
HDR.PROVIDER_CODE,
IMC.NAME  CLINICIANNAME,
DTL.CLINICIAN_CODE,
HDR.TRANSACTIONDATE PROCESSING_START_DATE,
to_DATE(HDR.LASTMODIFIEDON  ,'DD/MM/RRRR')   PROCESSING_END_DATE,
HDR.ENCOUNTER_START_DATE,
NVL(HDR.ENCOUNTER_END_DATE,HDR.ENCOUNTER_START_DATE)ENCOUNTER_END_DATE,
Count(*) NoOfcliams 
FROM (select * from IM_CLAIM_PROCESS_HEADER where CLAIM_STATUS=2 and
PROVIDER_CODE = Nvl(:PROVIDER_CODE,PROVIDER_CODE) AND
LASTMODIFIEDON BETWEEN :SDATE AND :EDATE
) HDR
JOIN IM_PROVIDERS IMPRO ON IMPRO.PROVIDERCODE = HDR.PROVIDER_CODE
JOIN IM_CLAIM_PROCESS_DETAIL DTL ON DTL.CLAIM_CODE = HDR.CLAIM_CODE and DTL.type not in (1,2)
LEFT JOIN IM_CLINICIANS IMC ON IMC.CDCODE = DTL.CLINICIAN_CODE         
GROUP BY  IMPRO.PROVIDERID,IMPRO.PROVIDERNAME,HDR.PROVIDER_CODE,IMC.NAME,DTL.CLINICIAN_CODE,HDR.ENCOUNTER_START_DATE,HDR.ENCOUNTER_END_DATE,HDR.TRANSACTIONDATE ,
to_DATE(HDR.LASTMODIFIEDON  ,'DD/MM/RRRR'))UTI


:PROVIDERCODE

SELECT PROVIDERCODE,PROVIDERID,PROVIDERNAME FROM IM_PROVIDERS
