SELECT
HNMPAY.PROVIDERID,
HNMPAY.PROVIDERNAME,
HNMPAY.PROVIDER_CODE,
DECODE(HNMPAY.MEMOTYPE,0,HNMPAY.PAIDAMOUNT,HNMPAY.PAIDAMOUNT*-1) PAIDAMOUNT,
HNMPAY.NOOFCLAIMS,                
HNMPAY.REF_NO AVERAGE
FROM (
SELECT IMPRO.PROVIDERNAME,
IMPRO.PROVIDERID,
IMPRO.PROVIDERCODE PROVIDER_CODE,
Sum(NVL((HDR.APPROVED_AMOUNT+(NVL((SELECT SUM(DENIEDAMOUNT)
FROM IM_DECLINEAMOUNT_VW DEC WHERE DEC.CLAIM_CODE = HDR.CLAIM_CODE),0))),0))PAIDAMOUNT,
Count(1) NOOFCLAIMS,JV.REF_NO,JV.MEMOTYPE
FROM IM_ENDPOSTCLAIMDTL CLMDET
JOIN IM_ENDORSEMENTPOSTING POS ON POS.ENDORESMENTCODE=CLMDET.ENDORESMENTCODE AND POS.AUTHORIZEDSTATUS=1 --AND POS.PROVIDERCODE IS NOT NULL
JOIN  IM_CLAIM_PROCESS_HEADER HDR ON CLMDET.CLAIMCODE=HDR.CLAIM_CODE
JOIN IM_NGI_JVPOSTING JV ON JV.CLAIMREFCODE = POS.ENDORESMENTCODE
JOIN IM_PROVIDERS IMPRO ON    IMPRO.PROVIDERCODE = HDR.PROVIDER_CODE
WHERE JV.REFDATE BETWEEN :SDATE AND :EDATE AND NVL(INCLUDE_CLAIM,0) = 0
AND IMPRO.PROVIDERCODE  = Nvl(:PROVIDERCODE,IMPRO.PROVIDERCODE)
GROUP BY
HDR.PROVIDER_CODE,
IMPRO.PROVIDERNAME,
IMPRO.PROVIDERID,
POS.PROVIDERCODE,
IMPRO.PROVIDERCODE,JV.REF_NO,JV.MEMOTYPE
) HNMPAY

ORDER BY PROVIDERNAME



:PROVIDERCODE

SELECT PROVIDERCODE,PROVIDERID,PROVIDERNAME FROM IM_PROVIDERS