
SELECT * FROM(SELECT PRO.PROVIDERCODE,(PRO.PROVIDERID || ' - ' || PRO.PROVIDERNAME) HNMNAME,IBC.BENEFIT_ID BENEFITID,
IBC.BENEFIT_NAME BENEFITNAME,
SUM(DTL.TOTAL) PAYABLEAMOUNT FROM IM_CLAIM_PROCESS_HEADER CPH
JOIN IM_PROVIDERS PRO ON PRO.PROVIDERCODE = CPH.PROVIDER_CODE
JOIN IM_CLAIM_PROCESS_DETAIL DTL ON DTL.CLAIM_CODE = CPH.CLAIM_CODE AND NVL(DTL.TYPE,0) = 0
JOIN IM_BENEFIT_CODES IBC ON IBC.BENEFIT_CODE = DTL.BENEFIT_CODE
JOIN IM_MEMBERS_MAT_VW IMM ON IMM.MEMBERCODE = CPH.MEMBER_CODE AND IMM.POLICYCODE = CPH.POLICYCODE AND IMM.CATEGORYCODE = CPH.CATEGORY_CODE
WHERE CPH.CLAIM_STATUS = 2 AND CPH.TRANSACTIONDATE BETWEEN :STARTDATE AND :ENDDATE 
AND CPH.PROVIDER_CODE = Nvl(:PROVIDER_CODE,CPH.PROVIDER_CODE) AND 
(IMP.TYPEE=1 AND IMP.POLICYCODE = Nvl(:POLICYCODE,IMP.POLICYCODE))
AND (IMP.TYPEE=2 AND IMP.POLICYCODE = Nvl(:INDIVIDUALPOLICYCODE,IMP.POLICYCODE)) AND IMM.MEMBERCODE = Nvl(:MEMBERCODE,IMM.MEMBERCODE)
AND DTL.BENEFIT_CODE = Nvl(:BENEFIT_CODE,DTL.BENEFIT_CODE)
GROUP BY PRO.PROVIDERID,PRO.PROVIDERNAME,IBC.BENEFIT_ID,IBC.BENEFIT_NAME,PRO.PROVIDERCODE) ORDER BY HNMNAME,BENEFITNAME



:PROVIDERCODE

SELECT PROVIDERID,PROVIDERNAME,PROVIDERCODE FROM IM_PROVIDERS

:POLICYCODE

SELECT POLICYCODE,POLICYID,POLICYNAME FROM IM_POLICY

:INDIVIDUALPOLICYCODE

SELECT INDIVIDUALPOLICYCODE,POLICYID,POLICYNAME FROM IM_INDIVIDUALPOLICY

:BENEFIT_CODE

SELECT BENEFIT_CODE,BENEFIT_ID,BENEFIT_NAME FROM IM_BENEFIT_CODES

:MEMBERCODE

SELECT MEMBERCODE,ACARDID,AMEMBERNAME FROM IM_MEMBERPOLICY