SELECT H.*,ROUND(LENGTHOFSTAY/NOOFPATIENT,2) AVERAGE FROM(SELECT HDR.PROVIDER_CODE,(PRO.PROVIDERID || ' - ' || PRO.PROVIDERNAME) HNMNAME,VER.CODE,VER.LONGDESC,
ROUND(SUM((ENCOUNTER_END_DATE - ENCOUNTER_START_DATE))) LENGTHOFSTAY,COUNT(*) NOOFPATIENT
 FROM IM_CLAIM_PROCESS_HEADER HDR
JOIN (SELECT CLAIM_CODE,VERSIONDETAILCODE,TYPE FROM IM_CLAIM_PROCESS_DETAIL WHERE NVL(TYPE,0) = 1) DTL ON DTL.CLAIM_CODE = HDR.CLAIM_CODE
JOIN (SELECT PROVIDERCODE,PROVIDERID,PROVIDERNAME FROM IM_PROVIDERS) PRO ON PRO.PROVIDERCODE   = HDR.PROVIDER_CODE
JOIN (SELECT DETAILCODE,CODE,LONGDESC FROM IM_VERSION_DETALIS) VER ON VER.DETAILCODE = DTL.VERSIONDETAILCODE
WHERE  HDR.TRANSACTIONDATE BETWEEN :SDATE AND :EDATE AND HDR.PROVIDER_CODE = Nvl(:PROVIDERCODE,HDR.PROVIDER_CODE)
AND DTL.VERSIONDETAILCODE = Nvl(:VERSIONDETAILCODE,DTL.VERSIONDETAILCODE) AND HDR.CLAIM_CODE IN(SELECT CLAIM_CODE FROM IM_CLAIM_PROCESS_DETAIL WHERE BENEFIT_CODE IN(
SELECT SUB_BENEFIT_CODE FROM IIM_BENEFIT_CODES_DET WHERE BENEFIT_CODE IN (10000000000000017,10000000000000035)))
GROUP BY HDR.PROVIDER_CODE,VER.CODE,PRO.PROVIDERID,PRO.PROVIDERNAME,VER.LONGDESC
) H WHERE LENGTHOFSTAY > 0


:PROVIDERCODE

SELECT PROVIDERID,PROVIDERNAME,PROVIDERCODE FROM IM_PROVIDERS

:VERSIONDETAILCODE

SELECT DETAILCODE,CODE,SHORTDESC FROM IM_VERSION_DETALIS