SELECT NVL(IMP.AMEMBERNAME,'REIMBURSEMENT CLAIMS') MEMBERNAME,NVL(HDR.CARDNO,NVL(POL.POLICYID,IPOL.POLICYID)) CARDNO,
NVL(POL.POLICYID,IPOL.POLICYID) POLICYID,
(NVL(SUBSTR(POL.POLICYID,INSTR(POL.POLICYID,'-')+1),SUBSTR(IPOL.POLICYID,INSTR(IPOL.POLICYID,'-')+1))) POLICYSERIAL,
NVL(SUBSTR(POL.POLICYID,0,4),SUBSTR(IPOL.POLICYID,0,4)) PRODUCT,
NVL(POL.POLICYNAME,IPOL.POLICYNAME) POLICYNAME,
HDR.CPNO CLAIMNO,HDR.ACR_FORM_NO CLAIMFORMNO,
HDR.ENCOUNTER_START_DATE TREATMENTDATE,
NVL((SELECT LISTAGG (IMVD.SHORTDESC, ',') WITHIN GROUP (ORDER BY IMVD.SHORTDESC) FROM IM_CLAIM_PROCESS_DETAIL DTL
LEFT JOIN IM_ACTIVITY_TYPES ACTTYP ON ACTTYP.TYPECODE=DTL.ACTIVITY_CODE
JOIN IM_VERSION_DETALIS IMVD ON IMVD.DETAILCODE = DTL.VERSIONDETAILCODE
WHERE ACTTYP.VALUE = -1 AND DTL.CLAIM_CODE = HDR.CLAIM_CODE GROUP BY DTL.CLAIM_CODE ),'PRINCIPAL') ICDCODES,
NVL(HDR.REQUEST_AMOUNT,0) FEEAMOUNT,NVL(HDR.DEDUCTABLEVALUE,0) DEDUCTABLEVALUE,NVL(HDR.CO_INS_VALUE,0) CO_INS_VALUE,
NVL((SELECT SUM(DENIEDAMOUNT) FROM IM_DECLINEAMOUNT_VW V WHERE V.CLAIM_CODE = HDR.CLAIM_CODE),0) DENAILVALUE,
NVL(HDR.APPROVED_AMOUNT,0) APPROVED_AMOUNT,
TO_DATE(:SDATE) FROMDATE,
TO_DATE(:EDATE) TODATE,
POL.GROUPCODE,
NVL(SUBSTR(POL.POLICYID,0,4),IPOL.POLICYID) GROUP_ID,
NVL(POL.POLICYNAME,IPOL.POLICYNAME) GROUP_NAME
--FROM IM_ENDORSEMENTPOSTING ENDO
--JOIN IM_ENDPOSTCLAIMDTL DET ON  ENDO.ENDORESMENTCODE = DET.ENDORESMENTCODE  AND TO_DATE(REFDATE,'DD/MM/RRRR')  BETWEEN TO_DATE(SDATE,'DD/MM/RRRR') AND TO_DATE(EDATE,'DD/MM/RRRR')
--JOIN IM_CLAIM_PROCESS_HEADER HDR ON  DET.CLAIMCODE = HDR.CLAIM_CODE
FROM IM_CLAIM_PROCESS_HEADER HDR
JOIN IM_MEMBERPOLICY IMP ON IMP.MEMBERPOLICYCODE = HDR.MEMBERPOLICYCODE
LEFT JOIN IM_POLICY POL ON POL.POLICYCODE = IMP.POLICYCODE AND IMP.TYPEE=1
LEFT JOIN IM_INDIVIDUALPOLICY IPOL ON IPOL.INDIVIDUALPOLICYCODE = IMP.POLICYCODE AND IMP.TYPEE=2
LEFT JOIN IM_GROUPS GRO ON GRO.GROUP_CODE=POL.GROUPCODE
WHERE NVL(HDR.ISREVERSED,0) = 0 AND HDR.REQUEST_TYPE IN (1,2) AND HDR.CLAIM_CODE IN
(SELECT VW.CLAIM_CODE FROM IM_DECLINEAMOUNT_VW VW WHERE VW.CLAIM_CODE = HDR.CLAIM_CODE) AND
HDR.LASTMODIFIEDON  BETWEEN :SDATE AND :EDATE AND   (IMP.TYPEE=1 AND IMP.POLICYCODE = Nvl(:POLICYCODE,IMP.POLICYCODE))
AND (IMP.TYPEE=2 AND IMP.POLICYCODE = Nvl(:INDIVIDUALPOLICYCODE,IMP.POLICYCODE)) AND HDR.PROVIDER_CODE = Nvl(:PROVIDERCODE,HDR.PROVIDER_CODE)
AND GRO.GROUP_CODE = Nvl(:GROUPCODE,GRO.GROUP_CODE) 
ORDER BY HDR.CARDNO ASC


:PROVIDERCODE

SELECT PROVIDERCODE,PROVIDERID,PROVIDERNAME FROM IM_PROVIDERS

:POLICYCODE

SELECT POLICYCODE,POLICYID,POLICYNAME FROM IM_POLICY

:INDIVIDUALPOLICYCODE

SELECT INDIVIDUALPOLICYCODE,POLICYID,POLICYNAME FROM IM_INDIVIDUALPOLICY

:GROUPCODE

SELECT GROUP_CODE,GROUP_NAME FROM IM_GROUPS    