SELECT CUPLOAD.* FROM (
SELECT IMPRO.PROVIDERID,
IMPRO.PROVIDERNAME,
IMPRO.PROVIDERCODE,
COUNT(*) NOFOFCLAIMS,
SUM(HDR.REQUEST_AMOUNT) CLAIMEDAMOUNT,
SUM(HDR.APPROVED_AMOUNT) PAIDAMOUNT,
SUM(HDR.ORGINALPATIENTSHARE) PATIENTSHARE 
FROM (SELECT * FROM  IM_CLAIM_PROCESS_HEADER  WHERE  CLAIM_STATUS=2  AND
TRANSACTIONDATE BETWEEN  :SDATE AND :EDATE  AND
PROVIDER_CODE = NVL(:PROVIDER_CODE,PROVIDER_CODE)
) HDR
JOIN IM_PROVIDERS IMPRO ON IMPRO.PROVIDERCODE = HDR.PROVIDER_CODE
GROUP BY IMPRO.PROVIDERID,IMPRO.PROVIDERNAME,IMPRO.PROVIDERCODE)CUPLOAD

WHERE CUPLOAD.PAIDAMOUNT<>0 AND CUPLOAD.PAIDAMOUNT >=:SNO AND CUPLOAD.PAIDAMOUNT<= DECODE(:ENO,0,CUPLOAD.PAIDAMOUNT,:ENO)



:PROVIDER_CODE

SELECT PROVIDERCODE,PROVIDERID,PROVIDERNAME FROM IM_PROVIDERS