SELECT
HDR.ENCOUNTER_START_DATE TREATMENTDATE,
NVL(HDR.ENCOUNTER_END_DATE,HDR.ENCOUNTER_START_DATE) TREATMENTENDDATE,
SUBSTR(IMPOL.APOLICYID,0,4)  POLICYID,
(IMPOL.APOLICYNAME) POLICYNAME,
(SELECT LISTAGG (IMVD.SHORTDESC, ',') WITHIN GROUP (ORDER BY IMVD.SHORTDESC) FROM IM_CLAIM_PROCESS_DETAIL DTL
LEFT JOIN IM_ACTIVITY_TYPES ACTTYP ON ACTTYP.TYPECODE=DTL.ACTIVITY_CODE
JOIN IM_VERSION_DETALIS IMVD ON IMVD.DETAILCODE = DTL.VERSIONDETAILCODE
WHERE ACTTYP.VALUE = -1 AND DTL.CLAIM_CODE = HDR.CLAIM_CODE AND DTL.TYPE = 1 GROUP BY DTL.CLAIM_CODE )  ICDCODE,
IMVRD.SHORTDESC DESCRIPTION,
TRUNC(MONTHS_BETWEEN(SYSDATE,IMPOL.ADATE_OF_BIRTH)/12) AS AGE 
FROM (SELECT * FROM IM_CLAIM_PROCESS_HEADER WHERE CLAIM_STATUS=2 AND
TRANSACTIONDATE BETWEEN :SDATE AND :EDATE
) HDR
JOIN IM_CLAIM_PROCESS_DETAIL DTL ON DTL.CLAIM_CODE = HDR.CLAIM_CODE AND DTL.TYPE <> 0
LEFT JOIN IM_VERSION_DETALIS  IMVRD ON IMVRD.DETAILCODE =  DTL.VERSIONDETAILCODE
LEFT JOIN IM_MEMBERPOLICY IMPOL ON IMPOL.POLICYCODE = HDR.POLICYCODE AND IMPOL.MEMBERCODE = HDR.MEMBER_CODE  AND IMPOL.CATEGORYCODE=HDR.CATEGORY_CODE
WHERE   (IMPOL.TYPEE = 1 AND IMPOL.POLICYCODE = Nvl(:POLICYCODE,IMPOL.POLICYCODE))
OR  (IMPOL.TYPEE = 2 AND  IMPOL.POLICYCODE = Nvl(:INDIVIDUALPOLICYCODE,IMPOL.POLICYCODE)) AND 
TRUNC(MONTHS_BETWEEN(SYSDATE,IMPOL.ADATE_OF_BIRTH)/12) >=:SNO AND TRUNC(MONTHS_BETWEEN(SYSDATE,IMPOL.ADATE_OF_BIRTH)/12)
<=DECODE(:ENO,0,TRUNC(MONTHS_BETWEEN(SYSDATE,IMPOL.ADATE_OF_BIRTH)/12),:ENO)



:POLICYCODE

SELECT POLICYCODE,POLICYID,POLICYNAME FROM IM_POLICY

:INDIVIDUALPOLICYCODE

:POLICYCODE

SELECT INDIVIDUALPOLICYCODEPOLICYCODE,POLICYID,POLICYNAME FROM IM_INDIVIDUALPOLICY