SELECT ICMB.RECEIPTNUMBER ACKNO,ICC.CARDNO CARDNO,IMM.AMEMBERNAME NAME,NVL(HDR.ACR_FORM_NO,ICMB.ACR_FORM_NO) CLAIMREFNO,ICB.RECEIVEDON ACKDATE,
HDR.CREATEDON PROCESSDATE,IEP.REFDATE PASSEDTOACCDATE,TO_cHAR((IEP.REFDATE - ICB.RECEIVEDON)) TATIME,
(SELECT LISTAGG (IMVD.SHORTDESC, ',')
WITHIN GROUP (ORDER BY IMVD.SHORTDESC)
FROM IM_CLAIM_PROCESS_DETAIL_DTL SDTL
JOIN IM_CLAIM_PROCESS_DETAIL DTL
ON DTL.ACTIVITY_DETAIL_CODE = SDTL.ACTIVITY_DETAIL_CODE AND SDTL.DENIEDFOR = 0
JOIN IM_VERSION_DETALIS IMVD
ON IMVD.DETAILCODE = SDTL.DENIAL_REASON
WHERE DTL.CLAIM_CODE = HDR.CLAIM_CODE
GROUP BY DTL.CLAIM_CODE)
DECLINECODE,HDR.REQUEST_AMOUNT CLAIMEDAMOUNT,HDR.APPROVED_AMOUNT APPROVEDAMT,HDR.OUTOFNETWORKPROVIDERNAME PROVIDERNAME
FROM IM_CLAIM_PROCESS_HEADER HDR
JOIN IM_MEMBERS_MAT_VW IMM ON IMM.MEMBERCODE = HDR.MEMBER_CODE AND IMM.POLICYCODE = HDR.POLICYCODE AND IMM.CATEGORYCODE = HDR.CATEGORY_CODE
JOIN IM_CORDPRINT ICC ON ICC.MEMBERPOLICYCODE = IMM.MEMBERPOLICYCODE
JOIN IM_CLAIMBATCH ICB ON ICB.CLAIMBATCHCODE = HDR.BATCHCODE
JOIN  IM_CLAIMMEMBERBATCH ICMB ON ICMB.CLAIMBATCHCODE = HDR.BATCHCODE AND ICMB.MEMBERCODE = HDR.MEMBER_CODE
AND ICMB.POLICYCODE = HDR.POLICYCODE AND ICMB.CATEGORYCODE = HDR.CATEGORY_CODE AND UPPER(ICMB.ACR_FORM_NO) = UPPER(HDR.ACR_FORM_NO)
JOIN IM_ENDPOSTCLAIMDTL IEPD ON IEPD.CLAIMCODE = HDR.CLAIM_CODE
JOIN IM_ENDORSEMENTPOSTING IEP ON IEP.ENDORESMENTCODE = IEPD.ENDORESMENTCODE
WHERE ICB.RECEIVEDON BETWEEN :SDATE AND :EDATE  IMM.MEMBERCODE  = Nvl(:MEMBERCODE,IMM.MEMBERCODE)
ORDER BY IMM.AMEMBERNAME   ASC;



:MEMBERCODE

SELECT MEMBERCODE,ACARDID,AMEMBERNAME FROM IM_MEMBERPOLICY