SELECT CPH.TRANSACTIONDATE UPLOADDATE,
SUM(DECODE(CPH.REQUEST_TYPE,1,(CPH.REQUEST_AMOUNT - CPH.ORGINALPATIENTSHARE),CPH.REQUEST_AMOUNT)) BILLEDAMT,
SUM(NVL((CPH.APPROVED_AMOUNT+(NVL((SELECT SUM(DENIEDAMOUNT) FROM IM_DECLINEAMOUNT_VW DEC
WHERE DEC.CLAIM_CODE = CPH.CLAIM_CODE),0))),0))  AMOUNTPAID,
(SELECT MAX(REF_NO) FROM IM_NGI_JVPOSTING WHERE CLAIMREFCODE=ENDO.ENDORESMENTCODE) DOCUMENTS,
(SELECT MAX(REFDATE) FROM IM_NGI_JVPOSTING WHERE CLAIMREFCODE=ENDO.ENDORESMENTCODE) DOCUMENTDATE,
REFDATE BANKTRANSFERDATE,
COUNT(*) NOOFCLAIMS,
((SELECT MAX(REFDATE) FROM IM_NGI_JVPOSTING WHERE CLAIMREFCODE=ENDO.ENDORESMENTCODE) - CPH.TRANSACTIONDATE) TATDAYS,1 TATAVG,
PRO.PROVIDERID,PRO.PROVIDERNAME 
FROM (SELECT * FROM IM_ENDORSEMENTPOSTING
WHERE SOURCECODE=0 AND AUTHORIZEDSTATUS<>0 AND REFDATE  BETWEEN :SDATE AND :EDATE)  ENDO
JOIN IM_ENDPOSTCLAIMDTL DET ON DET.ENDORESMENTCODE=ENDO.ENDORESMENTCODE
JOIN IM_CLAIM_PROCESS_HEADER CPH ON CPH.CLAIM_CODE=DET.CLAIMCODE
JOIN IM_PROVIDERS PRO ON PRO.PROVIDERCODE = CPH.PROVIDER_CODE
WHERE CPH.PROVIDER_CODE = Nvl(:PROVIDER_CODE,CPH.PROVIDER_CODE)
GROUP BY CPH.TRANSACTIONDATE,REFDATE,ENDO.ENDORESMENTCODE,PROVIDERID,PROVIDERNAME
HAVING SUM(APPROVED_AMOUNT)>=:SNO AND SUM(APPROVED_AMOUNT)>=DECODE(:ENO,0,SUM(APPROVED_AMOUNT),:ENO)



:PROVIDER_CODE


SELECT PROVIDERCODE,PROVIDERID,PROVIDERNAME FROM IM_PROVIDERS