SELECT PROVIDERID,PROVIDERNAME,IMC.LICENSEID,IMC.NAME,Count(*) FREQUENCY,Sum(Nvl(DTL.PRICE,0)),
Sum(Nvl(DTL.TOTAL,0)) PAIDAMOUNT FROM IM_CLAIM_PROCESS_DETAIL DTL
JOIN IM_CLAIM_PROCESS_HEADER HDR ON HDR.CLAIM_CODE = DTL.CLAIM_CODE
JOIN IM_PROVIDERS PRO ON PRO.PROVIDERCODE = HDR.PROVIDER_CODE
JOIN IM_CLINICIANS IMC ON IMC.CDCODE = DTL.CLINICIAN_CODE
WHERE VERSIONDETAILCODE IN
(SELECT DETAILCODE FROM IM_VERSION_DETALIS WHERE CODE='31231')
GROUP BY PROVIDERID,PROVIDERNAME,IMC.LICENSEID,IMC.NAME      


SELECT CARDNO,AMEMBERNAME,APOLICYID,APOLICYNAME,HDR.ACR_FORM_NO,INVOICENUMBER,To_Char(ENCOUNTER_START_DATE,'DD/MM/RRRR') TREATMENTDATE,
To_Char(TRANSACTIONDATE,'DD/MM/RRRR') TRANSACTIONDATE,IMC.LICENSEID,IMC.NAME,
REQUEST_AMOUNT,APPROVED_AMOUNT,PAYMENTREFNO,To_Char(PAYMENTREFDATE,'DD/MM/RRRR') PAYMENTDATE FROM IM_CLAIM_PROCESS_HEADER HDR 
JOIN IM_MEMBERPOLICY M ON M.MEMBERPOLICYCODE = HDR.MEMBERPOLICYCODE
JOIN IM_PROVIDERS PRO ON PRO.PROVIDERCODE = HDR.PROVIDER_CODE
JOIN IM_CLINICIANS IMC ON IMC.CDCODE = HDR.CDCODE
WHERE PROVIDERID='H125' AND 
HDR.CLAIM_CODE IN
(SELECT CLAIM_CODE FROM IM_CLAIM_PROCESS_DETAIL WHERE VERSIONDETAILCODE IN
(SELECT DETAILCODE FROM IM_VERSION_DETALIS WHERE CODE IN('Z38.00','Z38.01'))
AND CLAIM_CODE IN (SELECT CLAIM_CODE FROM IM_CLAIM_PROCESS_HEADER WHERE PROVIDER_CODE IN
(SELECT PROVIDERCODE FROM IM_PROVIDERS WHERE PROVIDERID = 'H125')))