SELECT   MEM.REF_NO,REFDATE,MEM.MANAGEDBY,UWYEAR,POLICYID,POLICYNAME,NETWORKNAME,ANNUALLIMIT,GROUPNAME,IPLIMIT,IPDEDUCTIBLE,IPCOINSURANCE,
OPLIMIT,OPDEDUCTIBLE,OPCOINSURANCE,DENTALLIMIT,DENTALDEDUCTIBLE,DENTALCOINSURANCE,OPTICALLIMIT,OPTICALDEDUCTIBLE,OPTICALCOINSURANCE,
MATLIMIT,MATDEDUCTIBLE,MATCOINSURANCE,ACARDID,AMEMBERNAME,RELATION,GENDER,NATIONALITY,DOB,INCEPTIONDATE,EXPIRYDATE,
TOTALPREMIUM,AGENTCOM,INTROCOM,TPAFEES FROM IM_UW_ACTUARY_MEM MEM
JOIN IM_UW_ACTUARY_COM COM ON COM.POLICYFINANCEPOSTINGCODE = MEM.POLICYFINANCEPOSTINGCODE
LEFT JOIN IM_EFORM_UW_PRC_LIMIT LIM ON LIM.POLICYCODE = MEM.ANNUALPOLICYCODE AND LIM.POLICYTYPE = MEM.ANNUALPOLICYTYPE
WHERE COM.MEMBERPOLICYCODE = MEM.MEMBERPOLICYCODE AND  COM.POLICYFINANCEPOSTINGCODE = MEM.POLICYFINANCEPOSTINGCODE  
AND LIM.CATEGORYCODE = MEM.CATEGORYCODE AND COM.REF_NO = MEM.REF_NO
UNION  
SELECT   MEM.REF_NO,REFDATE,MEM.MANAGEDBY,UWYEAR,POLICYID,POLICYNAME,NETWORKNAME,ANNUALLIMIT,GROUPNAME,IPLIMIT,IPDEDUCTIBLE,IPCOINSURANCE,
OPLIMIT,OPDEDUCTIBLE,OPCOINSURANCE,DENTALLIMIT,DENTALDEDUCTIBLE,DENTALCOINSURANCE,OPTICALLIMIT,OPTICALDEDUCTIBLE,OPTICALCOINSURANCE,
MATLIMIT,MATDEDUCTIBLE,MATCOINSURANCE,ACARDID,AMEMBERNAME,RELATION,GENDER,NATIONALITY,DOB,INCEPTIONDATE,EXPIRYDATE,
TOTALPREMIUM,AGENTCOM,INTROCOM,TPAFEES FROM IM_UW_ACTUARY_MEM MEM
JOIN IM_UW_ACTUARY_COM COM ON COM.POLICYFINANCEPOSTINGCODE = MEM.POLICYFINANCEPOSTINGCODE
LEFT JOIN IM_EFORM_UW_PRC_LIMIT LIM ON LIM.POLICYCODE = MEM.ANNUALPOLICYCODE AND LIM.POLICYTYPE = MEM.ANNUALPOLICYTYPE
WHERE COM.MEMBERPOLICYCODE = MEM.MEMBERPOLICYCODE AND  COM.POLICYFINANCEPOSTINGCODE = MEM.POLICYFINANCEPOSTINGCODE
AND MEM.CATEGORYCODE IS NULL AND COM.REF_NO = MEM.REF_NO
