Bucker Master :

select * from IM_POCKET_MASTER

Bucker Detail:

 SELECT POCDET.*,BEN.BENEFIT_ID BENEFITID, BEN.BENEFIT_NAME BENEFITNAME,GEN.CONSTANTNAME TYPENAME FROM 
 IM_POCKET_MASTER_DET POCDET  
 LEFT JOIN IM_BENEFIT_CODES BEN ON BEN.BENEFIT_CODE=POCDET.BENEFITCODE  
 LEFT JOIN GENCONSTANT GEN ON GEN.CONSTANTVALUE=POCDET.TYPECODE AND GEN.CATEGORY='NGIADDORREMOVE' AND 
 Upper(GEN.LANGUAGECODE)='EN-US' WHERE POCDET.POCKETCODE=100000000000000064