
DELETE FROM IM_CLAIM_PROCESS_DETAIL_DTL WHERE ACTIVITY_DETAIL_CODE IN
(SELECT ACTIVITY_DETAIL_CODE FROM IM_CLAIM_PROCESS_DETAIL WHERE CLAIM_CODE IN
(SELECT CLAIM_CODE FROM IM_CLAIM_PROCESS_HEADER
WHERE PROVIDER_CODE IN(SELECT PROVIDERCODE FROM IM_PROVIDERS WHERE PROVIDERID = 'M079')
AND TO_DATE(LASTMODIFIEDON,'DD/MM/RRRR') = TO_dATE('25/07/2016','DD/MM/RRRR')));

UPDATE IM_CLAIM_PROCESS_DETAIL SET DEDUCTIBLE_AMOUNT=0,COINSURANCE_AMOUNT=0,
TOTAL = 0,DENIAL_VALUE = 0,DENIAL_REASON = NULL,BENEFIT_CODE = NULL WHERE CLAIM_CODE IN
(SELECT CLAIM_CODE FROM IM_CLAIM_PROCESS_HEADER
WHERE PROVIDER_CODE IN(SELECT PROVIDERCODE FROM IM_PROVIDERS WHERE PROVIDERID = 'M079')
AND TO_DATE(LASTMODIFIEDON,'DD/MM/RRRR') = TO_DATE('25/07/2016','DD/MM/RRRR'));

UPDATE IM_CLAIM_PROCESS_HEADER SET CO_INS_VALUE = 0,DEDUCTABLEVALUE = 0,
APPROVED_AMOUNT = 0,DENAILVALUE = 0,CLAIM_STATUS = 1,AUTHORIZEDSTATUS = 0,
ISPOSTED = 0,FINANCE = 0 WHERE PROVIDER_CODE IN(SELECT PROVIDERCODE FROM IM_PROVIDERS WHERE PROVIDERID = 'M079')
AND TO_DATE(LASTMODIFIEDON,'DD/MM/RRRR') = TO_DATE('25/07/2016','DD/MM/RRRR')



DELETE FROM IM_CLAIM_PROCESS_DETAIL_DTL WHERE ACTIVITY_DETAIL_CODE IN
(SELECT ACTIVITY_DETAIL_CODE FROM IM_CLAIM_PROCESS_DETAIL WHERE CLAIM_CODE IN
(SELECT CLAIM_CODE FROM IM_CLAIM_PROCESS_HEADER
WHERE  ACR_FORM_NO='H2256167'));

UPDATE IM_CLAIM_PROCESS_DETAIL SET DEDUCTIBLE_AMOUNT=0,COINSURANCE_AMOUNT=0,
TOTAL = 0,DENIAL_VALUE = 0,DENIAL_REASON = NULL,BENEFIT_CODE = NULL WHERE CLAIM_CODE IN
(SELECT CLAIM_CODE FROM IM_CLAIM_PROCESS_HEADER
WHERE ACR_FORM_NO = 'H2256167');

UPDATE IM_CLAIM_PROCESS_HEADER SET CO_INS_VALUE = 0,DEDUCTABLEVALUE = 0,
APPROVED_AMOUNT = 0,DENAILVALUE = 0,CLAIM_STATUS = 1,AUTHORIZEDSTATUS = 0,
ISPOSTED = 0,FINANCE = 0 WHERE ACR_FORM_NO = 'H2256167'