USE [compassedumity]
GO
/****** Object:  StoredProcedure [dbo].[PRC_CLASS_POST_NOTIFICATION]    Script Date: 25-Oct-18 4:38:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[PRC_CLASS_POST_NOTIFICATION]  AS
DECLARE @MyCursor CURSOR; 
DECLARE @UserId varchar(255);
Declare @NotificationCount int;
DECLARE @UserPostID varchar(255); 
DECLARE @FeedBackType varchar(255);
DECLARE @UserPostFeedbackID varchar(255);
 
BEGIN 
SET @MyCursor = CURSOR FOR
select  Class_Post_Id,Posted_By From Edu_Class_posts where Notified = 'N'
 
OPEN @MyCursor
FETCH NEXT FROM @MyCursor
INTO @UserPostID, @UserId
  
WHILE @@FETCH_STATUS = 0
BEGIN  
INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),'CP',@UserPostID,'N',NULL,USER_ID FROM EDU_USERS WHERE USER_TYPE = 'SA'

INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),'CP',@UserPostID,'N',NULL,USER_ID FROM EDU_USERS WHERE USER_TYPE = 'A' AND USER_ID IN(
SELECT USER_ID FROM EDU_SCHOOL_MEMBERS WHERE SCHOOL_ID IN
(SELECT SCHOOL_ID FROM EDU_SCHOOL_MEMBERS WHERE USER_ID =@UserId))

INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),'CP',@UserPostID,'N',NULL,PARENT_USER_ID FROM EDU_PARENT_STUDENT WHERE STUDENT_USER_ID = @UserId

INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),'CP',@UserPostID,'N',NULL,PARENT_USER_ID FROM EDU_PARENT_STUDENT WHERE PARENT_USER_ID = @UserId

INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),'CP',@UserPostID,'N',NULL,USER_ID FROM EDU_USERS WHERE USER_ID IN(
SELECT USER_ID FROM EDU_CLASS_MEMBERS WHERE CLASS_ID IN
(SELECT CLASS_ID FROM EDU_CLASS_POSTS WHERE POSTED_BY =@UserId)) 

UPDATE EDU_CLASS_POSTS SET NOTIFIED = 'Y' WHERE Class_Post_Id = @UserPostID


FETCH NEXT FROM @MyCursor
INTO @UserPostID, @UserId
END; 
 
CLOSE @MyCursor ;
DEALLOCATE @MyCursor;
END;

BEGIN 
SET @MyCursor = CURSOR FOR
select  Class_Post_Id,Posted_By,Class_Post_FeedBack_Type,Class_Post_Feedback_ID From EDU_CLASS_POSTS_FEEDBACK where Notified = 'N'
 
OPEN @MyCursor
FETCH NEXT FROM @MyCursor
INTO @UserPostID, @UserId,@FeedBackType,@UserPostFeedbackID
  
WHILE @@FETCH_STATUS = 0
BEGIN  
INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),CONCAT('C',@FeedBackType),@UserPostID,'N',NULL,USER_ID FROM EDU_USERS WHERE USER_TYPE = 'SA'

INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),CONCAT('C',@FeedBackType),@UserPostID,'N',NULL,USER_ID FROM EDU_USERS WHERE USER_TYPE = 'A' AND USER_ID IN(
SELECT USER_ID FROM EDU_SCHOOL_MEMBERS WHERE SCHOOL_ID IN
(SELECT SCHOOL_ID FROM EDU_SCHOOL_MEMBERS WHERE USER_ID =@UserId))

INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),CONCAT('C',@FeedBackType),@UserPostID,'N',NULL,PARENT_USER_ID FROM EDU_PARENT_STUDENT WHERE STUDENT_USER_ID = @UserId

INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),CONCAT('C',@FeedBackType),@UserPostID,'N',NULL,PARENT_USER_ID FROM EDU_PARENT_STUDENT WHERE PARENT_USER_ID = @UserId

INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),'C',@UserPostID,'N',NULL,USER_ID FROM EDU_USERS WHERE USER_ID IN(
SELECT USER_ID FROM EDU_CLASS_MEMBERS WHERE CLASS_ID IN
(SELECT CLASS_ID FROM EDU_CLASS_POSTS WHERE POSTED_BY =@UserId))  

UPDATE EDU_CLASS_POSTS_FEEDBACK SET NOTIFIED = 'Y' WHERE Class_Post_Feedback_ID = @UserPostFeedbackID


FETCH NEXT FROM @MyCursor
INTO @UserPostID, @UserId,@FeedBackType,@UserPostFeedbackID
END; 
 
CLOSE @MyCursor ;
DEALLOCATE @MyCursor;
END;