SELECT * FROM(SELECT POLICYNO,CARDNO,CLIENTNAME,POLICYEFFECTIVEDATE,POLICYEXPIRYDATE,
CATEGORY_NAME,AMEMBERNAME,RELATION,PREMIUM,REFUNDPREMIUM,(PREMIUM-REFUNDPREMIUM) TOTALPREMIUM,
MEMBEREFFECTIVEDATE,MEMBEREXPIRYDATE,MEMBERORGINALEFFECTIVEDATE,ENDORSEMENTTYPE,POLICYTYPE FROM(
SELECT REPLACE(MEMPOL.APOLICYID,'-','/') POLICYNO,MEMPOL.ACARDID CARDNO,MEMPOL.APOLICYNAME CLIENTNAME,
TO_CHAR(MEMPOL.POLICYSTARTDDATE,'DD/MM/RRRR') POLICYEFFECTIVEDATE,TO_CHAR(MEMPOL.POLICYENDDDATE,'DD/MM/RRRR') POLICYEXPIRYDATE,
CAT.CATEGORY_NAME,MEMPOL.AMEMBERNAME,
DECODE (UPPER (GEN2.CONSTANTNAME),'SELF', 'PRINCIPAL','WIFE', 'SPOUSE','SON', 'CHILD','DAUGHTER', 'CHILD','DTR', 'CHILD','SPOUSE', 'SPOUSE')RELATION,
SUM(ADDPRE.PREMIUM_VALUE) PREMIUM,
0 REFUNDPREMIUM,
TO_CHAR(MEMPOL.MEMBERSTARTDATE,'DD/MM/RRRR') MEMBEREFFECTIVEDATE,
NULL MEMBEREXPIRYDATE,
TO_CHAR(MEM.MEMBERSINCE,'DD/MM/RRRR') MEMBERORGINALEFFECTIVEDATE,
DECODE(TO_CHAR(MEMPOL.MEMBERSTARTDATE,'DD/MM/RRRR'),TO_CHAR(MEMPOL.POLICYSTARTDDATE,'DD/MM/RRRR'),'INCEPTION','ADDITION') ENDORSEMENTTYPE,
DECODE(MEMPOL.TYPEE,1,'GROUP',2,'INDIVIDUAL') POLICYTYPE
FROM IM_MEMBERPOLICY MEMPOL
JOIN IM_MEMBERS MEM ON MEM.MEMBER_CODE = MEMPOL.MEMBERCODE
JOIN IM_MEMBERPOLICYPREMIUMDTL ADDPRE ON ADDPRE.MEMBERPOLICYCODE = MEMPOL.MEMBERPOLICYCODE 
LEFT JOIN IM_CATEGORIES CAT ON CAT.CATEGORY_CODE = MEMPOL.CATEGORYCODE
LEFT JOIN IM_POLICY POL ON POL.POLICYCODE = MEMPOL.POLICYCODE AND MEMPOL.TYPEE = 1
LEFT JOIN IM_INDIVIDUALPOLICY IPOL ON IPOL.INDIVIDUALPOLICYCODE = MEMPOL.POLICYCODE AND MEMPOL.TYPEE = 2
LEFT JOIN GENCONSTANT GEN2  ON  GEN2.CONSTANTVALUE = MEMPOL.ARELATION AND GEN2.CATEGORY = 'MEMBERRELATION'  AND UPPER (GEN2.LANGUAGECODE) = 'EN-US'
WHERE  (MEMPOL.MEMBERSTARTDATE > TO_DATE ('01/06/2015', 'DD/MM/RRRR') OR  MEMPOL.MEMBERENDDATE  > TO_DATE ('01/06/2015', 'DD/MM/RRRR'))
AND (MEMPOL.MEMBERSTARTDATE < TO_DATE ('01/11/2016', 'DD/MM/RRRR')  OR  MEMPOL.MEMBERENDDATE < TO_DATE ('01/11/2016', 'DD/MM/RRRR'))
AND (POL.OWNERCODE = 3 OR IPOL.OWNERCODE = 3) AND 
(CAT.CATEGORY_NAME LIKE '%AUH%' OR IPOL.INDIVIDUALPOLICYCODE IN(
SELECT INDIVIDUALPOLICYCODE FROM IM_NGIINDPOLICYCATEGORY WHERE PLANCODE IN
(SELECT PLAN_CODE FROM IM_PLANEMIRATES WHERE EMIRATECODE=100000000000001989)))
GROUP BY MEMPOL.APOLICYID,MEMPOL.ACARDID,MEMPOL.APOLICYNAME,MEMPOL.POLICYSTARTDDATE,MEMPOL.POLICYENDDDATE,
CAT.CATEGORY_NAME,MEMPOL.AMEMBERNAME,GEN2.CONSTANTNAME,MEMPOL.MEMBERSTARTDATE,MEMPOL.MEMBERENDDATE,MEM.MEMBERSINCE,MEMPOL.TYPEE
UNION
SELECT REPLACE(MEMPOL.APOLICYID,'-','/') POLICYNO,MEMPOL.ACARDID CARDNO,MEMPOL.APOLICYNAME CLIENTNAME,
TO_CHAR(MEMPOL.POLICYSTARTDDATE,'DD/MM/RRRR') POLICYEFFECTIVEDATE,TO_CHAR(MEMPOL.POLICYENDDDATE,'DD/MM/RRRR') POLICYEXPIRYDATE,
CAT.CATEGORY_NAME,MEMPOL.AMEMBERNAME,
DECODE (UPPER (GEN2.CONSTANTNAME),'SELF', 'PRINCIPAL','WIFE', 'SPOUSE','SON', 'CHILD','DAUGHTER', 'CHILD','DTR', 'CHILD','SPOUSE', 'SPOUSE')RELATION,
0 PREMIUM,
SUM(ADDPRE.PREMIUM_VALUE) REFUNDPREMIUM,
TO_CHAR(MEMPOL.MEMBERSTARTDATE,'DD/MM/RRRR') MEMBEREFFECTIVEDATE,
NVL(TO_CHAR(MEMPOL.MEMBERENDDATE,'DD/MM/RRRR'),TO_CHAR(MEMPOL.POLICYENDDDATE,'DD/MM/RRRR')) MEMBEREXPIRYDATE,
TO_CHAR(MEM.MEMBERSINCE,'DD/MM/RRRR') MEMBERORGINALEFFECTIVEDATE,'DELETION' ENDORSEMENTTYPE,
DECODE(MEMPOL.TYPEE,1,'GROUP',2,'INDIVIDUAL') POLICYTYPE
FROM IM_MEMBERPOLICY MEMPOL
JOIN IM_MEMBERS MEM ON MEM.MEMBER_CODE = MEMPOL.MEMBERCODE
JOIN IM_MEMPOLICYREFUNDPREMDTL ADDPRE ON ADDPRE.MEMBERPOLICYCODE = MEMPOL.MEMBERPOLICYCODE
LEFT JOIN IM_POLICY POL ON POL.POLICYCODE = MEMPOL.POLICYCODE AND MEMPOL.TYPEE = 1 
LEFT JOIN IM_INDIVIDUALPOLICY IPOL ON IPOL.INDIVIDUALPOLICYCODE = MEMPOL.POLICYCODE AND MEMPOL.TYPEE = 2
LEFT JOIN IM_CATEGORIES CAT ON CAT.CATEGORY_CODE = MEMPOL.CATEGORYCODE
LEFT JOIN GENCONSTANT GEN2  ON  GEN2.CONSTANTVALUE = MEMPOL.ARELATION AND GEN2.CATEGORY = 'MEMBERRELATION'  AND UPPER (GEN2.LANGUAGECODE) = 'EN-US'
WHERE  (MEMPOL.MEMBERSTARTDATE > TO_DATE ('01/06/2015', 'DD/MM/RRRR') OR MEMPOL.MEMBERENDDATE  > TO_DATE ('01/06/2015', 'DD/MM/RRRR'))
AND (MEMPOL.MEMBERSTARTDATE < TO_DATE ('01/11/2016', 'DD/MM/RRRR')  OR MEMPOL.MEMBERENDDATE  < TO_DATE ('01/11/2016', 'DD/MM/RRRR'))
AND (POL.OWNERCODE = 3 OR IPOL.OWNERCODE = 3) AND 
(CAT.CATEGORY_NAME LIKE '%AUH%' OR IPOL.INDIVIDUALPOLICYCODE IN(
SELECT INDIVIDUALPOLICYCODE FROM IM_NGIINDPOLICYCATEGORY WHERE PLANCODE IN
(SELECT PLAN_CODE FROM IM_PLANEMIRATES WHERE EMIRATECODE=100000000000001989)))
GROUP BY MEMPOL.APOLICYID,MEMPOL.ACARDID,MEMPOL.APOLICYNAME,MEMPOL.POLICYSTARTDDATE,MEMPOL.POLICYENDDDATE,
CAT.CATEGORY_NAME,MEMPOL.AMEMBERNAME,GEN2.CONSTANTNAME,MEMPOL.MEMBERSTARTDATE,MEMPOL.MEMBERENDDATE,MEM.MEMBERSINCE,MEMPOL.TYPEE
)) ORDER BY MEMBERORGINALEFFECTIVEDATE