CREATE TABLE HRMS_IN_OUT
(
  INOUTCODE             NUMBER(19)              NOT NULL,
  INOUTSERIALNO         NUMBER(38)              NOT NULL,
  LOCATION_ID           NUMBER(19)              NOT NULL,
  CREATEDIN             NUMBER(19)              NOT NULL,
  CREATEDON             DATE                    NOT NULL,
  CREATEDBY             NUMBER(19)              NOT NULL,
  EMPLOYEECODE          NUMBER(19),
  CARDNO                NVARCHAR2(20),
  IDWENROLLNUMBER       NVARCHAR2(20)           NOT NULL,
  TRANSACTIONDATE       DATE                    DEFAULT sysdate               NOT NULL,
  ATTENDANCEDEVICECODE  NUMBER(19)              NOT NULL,
  IDWVERIFYMODE         NUMBER                  NOT NULL,
  IDWINOUTMODE          NUMBER                  NOT NULL,
  IDWYEAR               NUMBER                  NOT NULL,
  IDWWORKCODE           NUMBER,
  IDWRESERVED           NUMBER,
  IDWMONTH              NUMBER                  NOT NULL,
  IDWDAY                NUMBER                  NOT NULL,
  IDWHOUR               NUMBER                  NOT NULL,
  IDWMINUTE             NUMBER                  NOT NULL,
  IDWSECOND             NUMBER                  NOT NULL,
  IDWMACHINENUMBER      NUMBER,
  DEVICETYPE            NUMBER                  NOT NULL,
  PROCESSED             NUMBER                  DEFAULT 0                     NOT NULL,
  ORG_ID                NUMBER(4)               DEFAULT 1,
  IPPROCESSED           NUMBER                  DEFAULT 0,
  PROCESSEDUPD          NUMBER,
  STATUS                VARCHAR2(1 BYTE)
)