SELECT POL.POLICYID,POL.POLICYNAME,TO_CHAR(POL.STARTDATE,'RRRR') UWYEAR,
PLA.PLAN_NAME,DTL.ALTLIMIT MAXLIMIT,IBC.BENEFIT_ID,IBC.BENEFIT_NAME,
GETPARENTBENEFIT(PBB.BENEFITCODE) PARENTBENEFIT,
PBB.LIMITS,
Decode(Nvl(PBB.CO_IN_VALUE,0),0,Nvl(DTL.CO_IN_VALUE,0),Nvl(PBB.CO_IN_VALUE,0)) COINSURANCEPERCENTAGE,
Decode(Nvl(PBB.OONCO_IN_VALUE,0),0,Nvl(DTL.OONCO_IN_VALUE,0),Nvl(PBB.OONCO_IN_VALUE,0)) OONCOINSURANCEPERCENTAGE,
Decode(Nvl(PBB.DEDECTABLEVALUE,0),0,Nvl(DTL.DEDECTABLEVALUE,0),Nvl(PBB.DEDECTABLEVALUE,0)) DEDECTABLEVALUE,
Decode(Nvl(PBB.OONDEDECTABLEVALUE,0),0,Nvl(DTL.OONDEDECTABLEVALUE,0),Nvl(PBB.OONDEDECTABLEVALUE,0))OONDEDECTABLEVALUE,
NET.NETWORKNAME  FROM IM_POLICY POL
LEFT JOIN IM_POLICY_CATEGORYDTL DTL ON DTL.POLICYCODE = POL.POLICYCODE
LEFT JOIN IM_PLANS PLA ON PLA.PLAN_CODE = DTL.PLANCODE
LEFT JOIN IM_POLICY_BENEFITSETTING PBB ON PBB.CATEGORYCODE = DTL.CATEGORYCODE AND POL.POLICYCODE = PBB.POLICYCODE
LEFT JOIN IM_BENEFIT_CODES IBC ON IBC.BENEFIT_CODE = PBB.BENEFITCODE 
LEFT JOIN IM_POLICYCOVEREDNETWORK IPCN ON IPCN.PCDCODE = DTL.PCDCODE
LEFT JOIN IM_NETWORKS NET ON NET.NETWORKCODE = IPCN.NETWORKCODE
UNION ALL
SELECT POL.POLICYID,POL.POLICYNAME,TO_CHAR(POL.STARTDATE,'RRRR') UWYEAR,
PLA.PLAN_NAME,DTL.ALTLIMIT MAXLIMIT,IBC.BENEFIT_ID,IBC.BENEFIT_NAME,
GETPARENTBENEFIT(PBB.BENEFITCODE) PARENTBENEFIT,
PBB.LIMITS,
Decode(Nvl(PBB.CO_IN_VALUE,0),0,Nvl(DTL.CO_IN_VALUE,0),Nvl(PBB.CO_IN_VALUE,0)) COINSURANCEPERCENTAGE,
Decode(Nvl(PBB.OONCO_IN_VALUE,0),0,Nvl(DTL.OONCO_IN_VALUE,0),Nvl(PBB.OONCO_IN_VALUE,0)) OONCOINSURANCEPERCENTAGE,
Decode(Nvl(PBB.DEDECTABLEVALUE,0),0,Nvl(DTL.DEDECTABLEVALUE,0),Nvl(PBB.DEDECTABLEVALUE,0)) DEDECTABLEVALUE,
Decode(Nvl(PBB.OONDEDECTABLEVALUE,0),0,Nvl(DTL.OONDEDECTABLEVALUE,0),Nvl(PBB.OONDEDECTABLEVALUE,0))OONDEDECTABLEVALUE,
NET.NETWORKNAME  FROM IM_INDIVIDUALPOLICY POL
LEFT JOIN  IM_NGIINDPOLICYCATEGORY DTL ON DTL.INDIVIDUALPOLICYCODE = POL.INDIVIDUALPOLICYCODE
LEFT JOIN IM_PLANS PLA ON PLA.PLAN_CODE = DTL.PLANCODE
LEFT JOIN IM_POLICY_BENEFITSETTING PBB ON PBB.CATEGORYCODE = DTL.CATEGORYCODE AND POL.INDIVIDUALPOLICYCODE = PBB.POLICYCODE
LEFT JOIN IM_BENEFIT_CODES IBC ON IBC.BENEFIT_CODE = PBB.BENEFITCODE     
LEFT JOIN IM_INDIVIDUALPOLICYNETWORK IPCN ON IPCN.POLICYCATEGORYCODE = DTL.POLICYCATEGORYCODE
LEFT JOIN IM_NETWORKS NET ON NET.NETWORKCODE = IPCN.NETWORKCODE 