SELECT * FROM(
SELECT MPOL.APOLICYID POLICYID,Nvl(HDR.CARDNO,MPOL.ACARDID) FMCCARDNO,MPOL.AMEMBERNAME FMCMEMBERNAME,NVL(HDR.FMCUNIQCLAIMID,HDR.INVOICENUMBER) UNIQ_CLAIM_ID,
HDR.ENCOUNTER_START_DATE TREATMENTSTARTDATE,HDR.ENCOUNTER_END_DATE TREATMENTENDDATE,HDR.PAYMENTREFDATE SETTLEMENTDATE,
HDR.REQUEST_AMOUNT INVOICE_AMOUNT,HDR.APPROVED_AMOUNT NETAMOUNT,(SELECT LISTAGG(IMVD.SHORTDESC, ',')
WITHIN GROUP (ORDER BY IMVD.SHORTDESC) FROM IM_CLAIM_PROCESS_DETAIL DTL
LEFT JOIN IM_ACTIVITY_TYPES ACTTYP ON ACTTYP.TYPECODE = DTL.ACTIVITY_CODE JOIN IM_VERSION_DETALIS IMVD ON IMVD.DETAILCODE = DTL.VERSIONDETAILCODE
WHERE ACTTYP.VALUE = -1 AND DTL.CLAIM_CODE = HDR.CLAIM_CODE GROUP BY DTL.CLAIM_CODE) FMCDIAGNOSIS,
DECODE(HDR.TREATMENT_TYPE,0,'IN-PATIENT','OUT-PATIENT') TREATMENTTYPE
FROM IM_CLAIM_PROCESS_HEADER HDR
LEFT JOIN IM_MEMBERPOLICY MPOL ON MPOL.MEMBERPOLICYCODE = HDR.MEMBERPOLICYCODE
WHERE MPOL.POLICYCODE NOT IN
(SELECT POLICYCODE FROM IM_POLICY WHERE OWNERCODE  IN(13)) AND  TO_CHAR(MPOL.POLICYSTARTDDATE ,'RRRR')= '2016'
AND HDR.MEMBERPOLICYCODE IN(SELECT MEMBERPOLICYCODE FROM(
SELECT HDR.MEMBERPOLICYCODE,Sum(APPROVED_AMOUNT) INVOICEAMOUNT FROM IM_CLAIM_PROCESS_HEADER  HDR
LEFT JOIN IM_MEMBERPOLICY MPOL ON MPOL.MEMBERPOLICYCODE = HDR.MEMBERPOLICYCODE
WHERE MPOL.POLICYCODE NOT IN
(SELECT POLICYCODE FROM IM_POLICY WHERE OWNERCODE  IN(13)) AND 
TO_CHAR(MPOL.POLICYSTARTDDATE ,'RRRR')= '2016' AND REQUEST_TYPE IN (1,2,3) AND
MPOL.TYPEE = 1 
AND PAYMENTREFDATE BETWEEN TO_DATE('01/01/2016','DD/MM/RRRR') AND TO_DATE('30/06/2017','DD/MM/RRRR') GROUP BY HDR.MEMBERPOLICYCODE
UNION ALL
SELECT HDR.MEMBERPOLICYCODE,Sum(APPROVED_AMOUNT) INVOICEAMOUNT FROM IM_CLAIM_PROCESS_HEADER  HDR
LEFT JOIN IM_MEMBERPOLICY MPOL ON MPOL.MEMBERPOLICYCODE = HDR.MEMBERPOLICYCODE
WHERE MPOL.POLICYCODE NOT IN
(SELECT POLICYCODE FROM IM_POLICY WHERE OWNERCODE  IN(13)) AND 
TO_CHAR(MPOL.POLICYSTARTDDATE ,'RRRR')= '2016' AND REQUEST_TYPE IN (1,2,3) AND
MPOL.TYPEE = 2
AND PAYMENTREFDATE BETWEEN TO_DATE('01/01/2016','DD/MM/RRRR')  AND TO_DATE('30/06/2017','DD/MM/RRRR') GROUP BY HDR.MEMBERPOLICYCODE
)
WHERE INVOICEAMOUNT > 100000) AND
REQUEST_TYPE IN (1,2,3) AND
PAYMENTREFDATE BETWEEN TO_DATE('01/01/2016','DD/MM/RRRR')  AND TO_DATE('30/06/2017','DD/MM/RRRR'))ORDER BY FMCCARDNO