SELECT POL.POLICYCODE,1 POLICYTYPECODE,'Group' POLICYTYPE,POL.POLICYID,POL.POLICYNAME,
POL.STARTDATE,POL.ENDDATE,
Decode(POL.AUTHORIZEDSTATUS,0,'Pending',1,'Approved') POLICYSTATUS,
Decode(PR.AUTHORIZEDSTATUS,0,'Pending',1,'Approved') AUTHORIZEDSTATUS,POL.AGENTCODE,POL.BROKERCODE,POL.GROUPCODE,
0 MEMBERCODE FROM IM_POLICY POL
LEFT JOIN IM_POLICY_RENEWAL PR ON PR.POLICYCODE = POL.POLICYCODE AND PR.TYPECODE = 1
UNION ALL
SELECT POL.INDIVIDUALPOLICYCODE POLICYCODE,2 POLICYTYPECODE,'Individual' POLICYTYPE,POL.POLICYID,POL.POLICYNAME,
POL.STARTDATE,POL.ENDDATE,
Decode(POL.AUTHORIZEDSTATUS,0,'Pending',1,'Approved') POLICYSTATUS,
Decode(PR.AUTHORIZEDSTATUS,0,'Pending',1,'Approved') AUTHORIZEDSTATUS,POL.AGENTCODE,POL.BROKERCODE,0 GROUPCODE,
POL.MEMBERCODE FROM IM_INDIVIDUALPOLICY POL
LEFT JOIN IM_POLICY_RENEWAL PR ON PR.POLICYCODE = POL.INDIVIDUALPOLICYCODE AND PR.TYPECODE = 2
