Indvidual PRoduction - 

select * from table(SF_PRODUNCTIONINDIVNEXTCARE('EN-US','YYNNNN','ALL',to_date('01-Jan-2016 00:00:00','DD-MON-YYYY HH24:MI:SS'),to_date('01-Nov-2016 00:00:00','DD-MON-YYYY HH24:MI:SS'),0,0,'ALL','ALL','ALL','ALL','2016'))


Group Production - 

select * from table(SF_NEXTCAREPRODUCTIONGROUPPOL('YYYNNNN','EN-US','ALL','ALL',to_date('01-Jan-2016 00:00:00','DD-MON-YYYY HH24:MI:SS'),to_date('01-Nov-2016 00:00:00','DD-MON-YYYY HH24:MI:SS'),0,0,'ALL','ALL','ALL','2016'))


SELECT * FROM(SELECT COUNT(*) CNT,GROUP_NAME FROM IM_REINS_MEMBERS MEM
LEFT JOIN IM_GROUPS GRP ON GRP.GROUP_CODE = MEM.PARENTGROUPCODE
WHERE CARDNO IN
(SELECT ACARDID FROM IM_MEMBERPOLICY WHERE MEMBERPOLICYCODE IN
(SELECT MEMBERPOLICYCODE FROM IM_POLICYFINANCEPOSTINGDTL WHERE POLICYFINANCEPOSTINGCODE IN
(SELECT POLICYFINANCEPOSTINGCODE FROM IM_POLICYFINANCEPOSTING WHERE FINANCENO = 37897)))
GROUP BY GROUP_NAME)ORDER BY CNT

 
SELECT * FROM(SELECT COUNT(*) CNT,SUBGROUP  FROM IM_TPAPRODUCTIONDTL
WHERE TPAPRODCUTIONHDR IN
(SELECT TPAPRODHDRCODE FROM IM_TPAPRODUCTION_HDR WHERE REFNO = 159) AND NGI_POLICY_NO = '1095-1'
GROUP BY SUBGROUP)ORDER BY CNT


declare l_rules varchar2(500);
begin
l_rules:=updatealzah(1);
DBMS_OUTPUT.PUT_LINE(l_rules);
end;