SELECT POL.POLICYID,POL.POLICYNAME,GEN1.CONSTANTNAME,TO_CHAR(POL.STARTDATE,'RRRR')UWYEAR,TRT.TREATYNAME,GEN.CONSTANTNAME FROM IM_POLICY POL
JOIN IM_POLICY_INSURER_DTL DTL ON DTL.POLICYCODE = POL.POLICYCODE
LEFT JOIN IM_POLICY_INSURER_SUBDTL SDTL ON DTL.POLICYINSURERDTLCODE = SDTL.POLICYINSURERDTLCODE
LEFT JOIN IM_TREATY_HDR TRT ON TRT.TREATYHDRCODE = SDTL.TREATYHDRCODE
LEFT JOIN GENCONSTANT GEN ON GEN.CONSTANTVALUE = SDTL.PREMIUMTYPE AND UPPER(GEN.LANGUAGECODE) = 'EN-US' AND GEN.CATEGORY = 'PREMIUMTYPES'
LEFT JOIN GENCONSTANT GEN1 ON GEN1.CONSTANTVALUE = POL.OWNERCODE AND UPPER(GEN1.LANGUAGECODE) = 'EN-US' AND GEN1.CATEGORY = 'NGIQUOTATIONTYPE'
--WHERE SYSDATE BETWEEN POL.STARTDATE AND POL.ENDDATE