Activity TYPE :

SELECT LOOKUP_CODE,VALUE FROM FND_LOOKUP_VALUES  WHERE  LOOKUP_TYPE='IM_TRUEDOC_ACTIVITY_TYPE';


CPT Code :

SELECT DETAILCODE,CODE,SHORTDESC FROM IM_VERSION_DETALIS

TYPE :

SELECT LOOKUP_CODE,VALUE FROM FND_LOOKUP_VALUES  WHERE  LOOKUP_TYPE='IM_TRUEDOC_TYPE';


