Policy TYPE :

SELECT LOOKUP_CODE,VALUE FROM FND_LOOKUP_VALUES  WHERE  LOOKUP_TYPE='POLICYTYPE';


Policy ID :

SELECT * FROM (SELECT POLICYCODE,0 POLICTYPE,POLICYID,POLICYNAME FROM IM_POLICY
WHERE  OWNERCODE IN(3,13,21) AND  SYSDATE BETWEEN STARTDATE AND ENDDATE
UNION ALL
SELECT INDIVIDUALPOLICYCODE,1 POLICTYPE,POLICYID,POLICYNAME FROM IM_INDIVIDUALPOLICY
WHERE OWNERCODE IN(3,13,21) AND SYSDATE BETWEEN STARTDATE AND ENDDATE)

Category Name :

SELECT CATEGORY_CODE,CATEGORY_ID FROM IM_CATEGORIES


Card No :

SELECT MEMBER_CODE,CARDNO,FIRST_NAME||' '||MIDDLENAME||' ' ||LAST_NAME FROM IM_MEMBERS




Note : 


In the Above Queries First Field is Value Field Others are Display Field