SELECT * FROM(SELECT ACC.*,SF_GETACTUARYAGNCOMMISSION_FNC(POLICYFINANCEPOSTINGCODE,REF_NO,AMOUNT, TOTALPREMIUM) AS AGENTCOM,
SF_GETACTUARYINTROCOMM_FNC(POLICYFINANCEPOSTINGCODE,REF_NO,AMOUNT,TOTALPREMIUM) AS INTROCOM,
CASE WHEN TOTALPREMIUM > 0 THEN 
ABS(ROUND(NVL(TOTALPREMIUM,0)*(NGIFEESPERCENTAGE/100),2))*-1
ELSE
ABS(ROUND(NVL(TOTALPREMIUM,0)*(NGIFEESPERCENTAGE/100),2)) END  NGI_FEES FROM(
SELECT M.*,(ADDPREMIUM+REFUNDPREMIUM)TOTALPREMIUM FROM (SELECT  JV.REF_NO,JV.REFDATE,IMP.ACARDID,
IMP.AMEMBERNAME,To_Char(IMP.MEMBERSTARTDATE,'RRRR') ISSUEDYEAR,
Nvl(POL.POLICYID,IPOL.POLICYID)POLICYID,Nvl(POL.POLICYNAME,IPOL.POLICYNAME)POLICYNAME,
To_Char(IMP.MEMBERSTARTDATE,'DD/MM/RRRR') INCEPTIONDATE,To_Char(Nvl(IMP.MEMBERENDDATE,IMP.POLICYENDDDATE),'DD/MM/RRRR') EXPIRYDATE,
(SELECT OWNERNAME FROM GETPOLICYNAME_VW WHERE POLICYCODE  = NVL(POL.POLICYCODE,IPOL.INDIVIDUALPOLICYCODE) AND TYPEE = Decode(JV.POLICYTYPE,0,1,2)) MANAGEDBY,
Decode(Nvl(JV.REVERSEJVCODE,0),0,(NVL(ABS(DTL.ADDPREMIUM),0)),(NVL(ABS(DTL.ADDPREMIUM),0))*-1) ADDPREMIUM,
Decode(Nvl(JV.REVERSEJVCODE,0),0,(NVL(ABS(DTL.REFUNDPREMIUM),0))*-1,(NVL(ABS(DTL.REFUNDPREMIUM),0))) REFUNDPREMIUM,
(SELECT GETACTUARYIPPREMIUM(DTL.MEMBERPOLICYCODE,DTL.POLICYFINANCEPOSTINGCODE,1) FROM DUAL) IPPREMIUM,
(SELECT GETACTUARYOPPREMIUM(DTL.MEMBERPOLICYCODE,DTL.POLICYFINANCEPOSTINGCODE,2) FROM DUAL) OPPREMIUM,
TO_CHAR(Nvl(POL.STARTDATE,IPOL.STARTDATE),'RRRR') UWYEAR,
DECODE(JV.MEMOTYPE,1,NVL(POL.NGI_FEES,IPOL.NGI_FEES),NVL(POL.NGI_FEES,IPOL.NGI_FEES)*1)  NGIFEESPERCENTAGE,
JV.AMOUNT,DTL.POLICYFINANCEPOSTINGCODE FROM 
IM_NGI_JVPOSTING JV
JOIN IM_POLICYFINANCEPOSTINGDTL DTL ON DTL.POLICYFINANCEPOSTINGCODE = JV.REF_CODE
LEFT JOIN IM_MEMBERPOLICY IMP ON IMP.MEMBERPOLICYCODE = DTL.MEMBERPOLICYCODE
JOIN IM_MEMBERS IM ON IM.MEMBER_CODE = IMP.MEMBERCODE
LEFT JOIN IM_POLICY POL ON POL.POLICYCODE = JV.POLICYCODE AND JV.POLICYTYPE = 0
LEFT JOIN IM_INDIVIDUALPOLICY IPOL ON IPOL.INDIVIDUALPOLICYCODE = JV.POLICYCODE AND JV.POLICYTYPE = 1 
WHERE  JV.REF_CODE <> 100000000000035132 AND JV.JVPOSTINGCODE NOT IN(SELECT * FROM IM_REVERSE_DOC_06) AND   JVPREMIUMTYPE = 0 
AND REFDATE BETWEEN TO_DATE('01/10/2016','DD/MM/RRRR')
AND TO_DATE('31/10/2016','DD/MM/RRRR') AND JV.REF_CODE = DTL.POLICYFINANCEPOSTINGCODE  AND DTL.MEMBERPOLICYCODE = IMP.MEMBERPOLICYCODE
AND NVL(IM.PARENTGROUPCODE,IM.GROUP_CODE) =  JV.GROUPCODE  AND   JV.GROUPCODE  IS NOT NULL
UNION ALL
SELECT  JV.REF_NO,JV.REFDATE,IMP.ACARDID,
IMP.AMEMBERNAME,To_Char(IMP.MEMBERSTARTDATE,'RRRR') ISSUEDYEAR,
Nvl(POL.POLICYID,IPOL.POLICYID)POLICYID,Nvl(POL.POLICYNAME,IPOL.POLICYNAME)POLICYNAME,
To_Char(IMP.MEMBERSTARTDATE,'DD/MM/RRRR') INCEPTIONDATE,To_Char(Nvl(IMP.MEMBERENDDATE,IMP.POLICYENDDDATE),'DD/MM/RRRR') EXPIRYDATE,
(SELECT OWNERNAME FROM GETPOLICYNAME_VW WHERE POLICYCODE  = NVL(POL.POLICYCODE,IPOL.INDIVIDUALPOLICYCODE) AND TYPEE = Decode(JV.POLICYTYPE,0,1,2)) MANAGEDBY,
Decode(Nvl(JV.REVERSEJVCODE,0),0,(NVL(ABS(DTL.ADDPREMIUM),0)),(NVL(ABS(DTL.ADDPREMIUM),0))*-1) ADDPREMIUM,
Decode(Nvl(JV.REVERSEJVCODE,0),0,(NVL(ABS(DTL.REFUNDPREMIUM),0))*-1,(NVL(ABS(DTL.REFUNDPREMIUM),0))) REFUNDPREMIUM,
(SELECT GETACTUARYIPPREMIUM(DTL.MEMBERPOLICYCODE,DTL.POLICYFINANCEPOSTINGCODE,1) FROM DUAL) IPPREMIUM,
(SELECT GETACTUARYOPPREMIUM(DTL.MEMBERPOLICYCODE,DTL.POLICYFINANCEPOSTINGCODE,2) FROM DUAL) OPPREMIUM,
TO_CHAR(Nvl(POL.STARTDATE,IPOL.STARTDATE),'RRRR') UWYEAR,
DECODE(JV.MEMOTYPE,1,NVL(POL.NGI_FEES,IPOL.NGI_FEES)*-1,NVL(POL.NGI_FEES,IPOL.NGI_FEES)*1)  NGIFEESPERCENTAGE,
JV.AMOUNT,DTL.POLICYFINANCEPOSTINGCODE FROM 
IM_NGI_JVPOSTING JV
JOIN IM_POLICYFINANCEPOSTINGDTL DTL ON DTL.POLICYFINANCEPOSTINGCODE = JV.REF_CODE
LEFT JOIN IM_MEMBERPOLICY IMP ON IMP.MEMBERPOLICYCODE = DTL.MEMBERPOLICYCODE
JOIN IM_REINS_MEMBERS IM ON IM.MEMBER_CODE = IMP.REINSMEMBERCODE
LEFT JOIN IM_POLICY POL ON POL.POLICYCODE = JV.POLICYCODE AND JV.POLICYTYPE = 0
LEFT JOIN IM_INDIVIDUALPOLICY IPOL ON IPOL.INDIVIDUALPOLICYCODE = JV.POLICYCODE AND JV.POLICYTYPE = 1 
WHERE  JV.REF_CODE <> 100000000000035132 AND JV.JVPOSTINGCODE NOT IN(SELECT * FROM IM_REVERSE_DOC_06) AND  JVPREMIUMTYPE = 0 
AND REFDATE BETWEEN TO_DATE('01/10/2016','DD/MM/RRRR')
AND TO_DATE('31/10/2016','DD/MM/RRRR') AND JV.REF_CODE = DTL.POLICYFINANCEPOSTINGCODE  AND DTL.MEMBERPOLICYCODE = IMP.MEMBERPOLICYCODE
AND NVL(IM.PARENTGROUPCODE,IM.GROUP_CODE) =  JV.GROUPCODE  AND   JV.GROUPCODE  IS NOT NULL
UNION ALL
SELECT  JV.REF_NO,JV.REFDATE,Nvl(IMP.ACARDID,'DELMEMBER')ACARDID,IMP.AMEMBERNAME,To_Char(Nvl(IMP.MEMBERSTARTDATE,JV.REFDATE),'RRRR') ISSUEDYEAR,
Nvl(POL.POLICYID,IPOL.POLICYID)POLICYID,Nvl(POL.POLICYNAME,IPOL.POLICYNAME)POLICYNAME,
To_Char(IMP.MEMBERSTARTDATE,'DD/MM/RRRR') INCEPTIONDATE,To_Char(Nvl(IMP.MEMBERENDDATE,IMP.POLICYENDDDATE),'DD/MM/RRRR') EXPIRYDATE,
(SELECT OWNERNAME FROM GETPOLICYNAME_VW WHERE POLICYCODE  = NVL(POL.POLICYCODE,IPOL.INDIVIDUALPOLICYCODE) AND TYPEE = Decode(JV.POLICYTYPE,0,1,2)) MANAGEDBY,
Decode(Nvl(JV.REVERSEJVCODE,0),0,(NVL(ABS(DTL.ADDPREMIUM),0)),(NVL(ABS(DTL.ADDPREMIUM),0))*-1) ADDPREMIUM,
Decode(Nvl(JV.REVERSEJVCODE,0),0,(NVL(ABS(DTL.REFUNDPREMIUM),0))*-1,(NVL(ABS(DTL.REFUNDPREMIUM),0))) REFUNDPREMIUM,
(SELECT GETACTUARYIPPREMIUM(DTL.MEMBERPOLICYCODE,DTL.POLICYFINANCEPOSTINGCODE,1) FROM DUAL) IPPREMIUM,
(SELECT GETACTUARYOPPREMIUM(DTL.MEMBERPOLICYCODE,DTL.POLICYFINANCEPOSTINGCODE,2) FROM DUAL) OPPREMIUM,
TO_CHAR(Nvl(POL.STARTDATE,IPOL.STARTDATE),'RRRR') UWYEAR,
DECODE(JV.MEMOTYPE,1,NVL(POL.NGI_FEES,IPOL.NGI_FEES)*-1,NVL(POL.NGI_FEES,IPOL.NGI_FEES)*1)  NGIFEESPERCENTAGE,
JV.AMOUNT,DTL.POLICYFINANCEPOSTINGCODE FROM 
IM_NGI_JVPOSTING JV
JOIN IM_POLICYFINANCEPOSTINGDTL DTL ON DTL.POLICYFINANCEPOSTINGCODE = JV.REF_CODE
LEFT JOIN IM_MEMBERPOLICY IMP ON IMP.MEMBERPOLICYCODE = DTL.MEMBERPOLICYCODE
LEFT JOIN IM_POLICY POL ON POL.POLICYCODE = JV.POLICYCODE AND JV.POLICYTYPE = 0
LEFT JOIN IM_INDIVIDUALPOLICY IPOL ON IPOL.INDIVIDUALPOLICYCODE = JV.POLICYCODE AND JV.POLICYTYPE = 1 
WHERE  JV.REF_CODE <> 100000000000035132 AND  JV.JVPOSTINGCODE NOT IN(SELECT * FROM IM_REVERSE_DOC_06) AND JVPREMIUMTYPE = 0 
AND REFDATE BETWEEN TO_DATE('01/10/2016','DD/MM/RRRR')
AND TO_DATE('31/10/2016','DD/MM/RRRR') AND JV.REF_CODE = DTL.POLICYFINANCEPOSTINGCODE
AND JV.GROUPCODE  IS NULL 
 )M)ACC) 