USE [compassedumity]
GO
/****** Object:  StoredProcedure [dbo].[PRC_USER_POST_NOTIFICATION]    Script Date: 25-Oct-18 4:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[PRC_USER_POST_NOTIFICATION]  AS
DECLARE @MyCursor CURSOR; 
DECLARE @UserId varchar(255);
Declare @NotificationCount int;
DECLARE @UserPostID varchar(255); 
DECLARE @FeedBackType varchar(255);
DECLARE @UserPostFeedbackID varchar(255);
 
BEGIN 
SET @MyCursor = CURSOR FOR
select  User_Post_Id,User_ID From Edu_User_posts where Notified = 'N'
 
OPEN @MyCursor
FETCH NEXT FROM @MyCursor
INTO @UserPostID, @UserId
  
WHILE @@FETCH_STATUS = 0
BEGIN  
INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),'UP',@UserPostID,'N',NULL,USER_ID FROM EDU_USERS WHERE USER_TYPE = 'SA'

INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),'UP',@UserPostID,'N',NULL,USER_ID FROM EDU_USERS WHERE USER_TYPE = 'A' AND USER_ID IN(
SELECT USER_ID FROM EDU_SCHOOL_MEMBERS WHERE SCHOOL_ID IN
(SELECT SCHOOL_ID FROM EDU_SCHOOL_MEMBERS WHERE USER_ID =@UserId))

INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),'UP',@UserPostID,'N',NULL,PARENT_USER_ID FROM EDU_PARENT_STUDENT WHERE STUDENT_USER_ID = @UserId

INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),'UP',@UserPostID,'N',NULL,PARENT_USER_ID FROM EDU_PARENT_STUDENT WHERE PARENT_USER_ID = @UserId

INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),'UP',@UserPostID,'N',NULL,USER_ID FROM EDU_USER_FRIENDS WHERE FRIEND_USER_ID = @UserId

UPDATE EDU_USER_POSTS SET NOTIFIED = 'Y' WHERE USER_POST_ID = @UserPostID


FETCH NEXT FROM @MyCursor
INTO @UserPostID, @UserId
END; 
 
CLOSE @MyCursor ;
DEALLOCATE @MyCursor;
END;

BEGIN 
SET @MyCursor = CURSOR FOR
select  User_Post_Id,Posted_By,User_Post_FeedBack_Type,User_Post_Feedback_ID From EDU_USER_POSTS_FEEDBACK where Notified = 'N'
 
OPEN @MyCursor
FETCH NEXT FROM @MyCursor
INTO @UserPostID, @UserId,@FeedBackType,@UserPostFeedbackID
  
WHILE @@FETCH_STATUS = 0
BEGIN  
INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),CONCAT('U',@FeedBackType),@UserPostID,'N',NULL,USER_ID FROM EDU_USERS WHERE USER_TYPE = 'SA'

INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),CONCAT('U',@FeedBackType),@UserPostID,'N',NULL,USER_ID FROM EDU_USERS WHERE USER_TYPE = 'A' AND USER_ID IN(
SELECT USER_ID FROM EDU_SCHOOL_MEMBERS WHERE SCHOOL_ID IN
(SELECT SCHOOL_ID FROM EDU_SCHOOL_MEMBERS WHERE USER_ID =@UserId))

INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),CONCAT('U',@FeedBackType),@UserPostID,'N',NULL,PARENT_USER_ID FROM EDU_PARENT_STUDENT WHERE STUDENT_USER_ID = @UserId

INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),CONCAT('U',@FeedBackType),@UserPostID,'N',NULL,PARENT_USER_ID FROM EDU_PARENT_STUDENT WHERE PARENT_USER_ID = @UserId

INSERT INTO EDU_USER_NOTIFICATIONS
SELECT GETDATE(),CONCAT('U',@FeedBackType),@UserPostID,'N',NULL,USER_ID FROM EDU_USER_FRIENDS WHERE FRIEND_USER_ID = @UserId

UPDATE EDU_USER_POSTS_FEEDBACK SET NOTIFIED = 'Y' WHERE User_Post_Feedback_ID = @UserPostFeedbackID


FETCH NEXT FROM @MyCursor
INTO @UserPostID, @UserId,@FeedBackType,@UserPostFeedbackID
END; 
 
CLOSE @MyCursor ;
DEALLOCATE @MyCursor;
END;  