SELECT * FROM (
SELECT TO_DATE(:SDATE,'DD/MM/RRRR')  FROMDATE,
TO_DATE(:EDATE,'DD/MM/RRRR') TODATE,
NVL(AGT.AGENTCODE,BRK.BROKERCODE)  AGENTCODE,
NVL(POL.POLICYID,INDPOL.POLICYID) PRODUCTCODE,
NVL(POL.POLICYNAME,INDPOL.POLICYNAME) PRODUCTNAME,
NVL(GRO.GROUP_ID,MEM.MEMBER_ID) CUSTOMERCODE ,
NVL(GRO.GROUP_NAME,MEM.FIRST_NAME) CUSTOMERANME ,
NVL(AGT.AGENT_ID,BRK.BROKER_ID)  AGENTID,
NVL(AGT.AGENT_NAME_EN,BRK.BROKER_NAME_EN)  AGENTNAME,
JV.REFDATE DOCUMENTDATE,
JV.REF_NO DOCUMENTNO,
JV.ACCOUNTNO,JV.BINCODE,AORG.ORGANIZATION_NAME,(ABS(JV.AMOUNT) * DECODE(MEMOTYPE,0,-1,1)) AMOUNT,
(CASE JV.JVPREMIUMTYPE WHEN 0 THEN 'PREMIUM' WHEN 1 THEN 'COMMISSION' END) DOCUMENTTYPE FROM IM_NGI_JVPOSTING JV
LEFT JOIN IM_POLICY POL ON POL.POLICYCODE=JV.POLICYCODE AND REF_TYPE=0
LEFT JOIN IM_INDIVIDUALPOLICY INDPOL ON INDPOL.INDIVIDUALPOLICYCODE=JV.POLICYCODE AND REF_TYPE=1
LEFT JOIN IM_GROUPS GRO ON GRO.GROUP_CODE=POL.GROUPCODE
LEFT JOIN IM_MEMBERS MEM ON MEM.MEMBER_CODE=POL.MEMBERCODE
LEFT JOIN IM_AGENTS AGT ON  AGT.AGENTCODE=NVL(POL.AGENTCODE,INDPOL.AGENTCODE)
LEFT JOIN IM_BROKERS BRK ON  BRK.BROKERCODE =NVL(POL.BROKERCODE,INDPOL.BROKERCODE)
LEFT JOIN HR_ORGANIZATIONS_D AORG ON AORG.ORGANIZATIONS_CODE=(NVL(NVL(POL.BRANCHCODE,INDPOL.BRANCHCODE),DECODE(NVL(POL.BILLINGTYPE,INDPOL.BILLINGTYPE),0, AGT.BRANCHCODE,1,BRK.BRANCHCODE,NVL(NVL(POL.BRANCHCODE,INDPOL.BRANCHCODE),NVL(AGT.BRANCHCODE,BRK.BRANCHCODE)))))
WHERE JV.JVPREMIUMTYPE = 0 AND   JV.BINCODE IS NOT NULL  AND
JV.REFDATE BETWEEN :SDATE AND :EDATE AND
AGT.AGENTCODE  = NVL(:P_AGENTCODE,AGT.AGENTCODE) AND BRK.BROKERCODE = Nvl(:P_BROKERCODE,BRK.BROKERCODE)  
) ORDER BY AGENTCODE
