Master :

SELECT BENSET.*,NVL(POL.POLICYID,INDPOL.POLICYID) POLICYID, 
NVL(POL.POLICYNAME,INDPOL.POLICYNAME) POLICYNAME,PLA.PLAN_NAME,BEN.BENEFIT_ID BENEFITID,BEN.BENEFIT_NAME BENEFITNAME,  
GEN.CONSTANTNAME APPLICABLEFORNAME,GEN1.CONSTANTNAME PROVIDERTYPENAME,GEN2.CONSTANTNAME DEDECTABLETYPENAME,
GEN3.CONSTANTNAME LIMITTYPENAME,  GEN4.CONSTANTNAME COINTYPENAME,GEN5.CONSTANTNAME PERIODTYPENAME,
LOK1.LOOKUPNAME ROOMTYPENAME,GEN7.CONSTANTNAME OONCOINTYPENAME,  GEN8.CONSTANTNAME OONDEDECTABLETYPENAME ,
GENN1.CONSTANTNAME EMGDETECTWINETWTYPENAME,GENN2.CONSTANTNAME EMGDETECTOONETWTYPENAME,CAT.CATEGORY_NAME,
GENM1.CONSTANTNAME WNSLTYPENAME,GENM2.CONSTANTNAME ONSLTYPENAME FROM IM_POLICY_BENEFITSETTING BENSET 
LEFT JOIN IM_POLICY POL ON POL.POLICYCODE=DECODE(BENSET.REQTYPE,0,BENSET.POLICYCODE,0) 
LEFT JOIN IM_INDIVIDUALPOLICY INDPOL ON INDPOL.INDIVIDUALPOLICYCODE=DECODE(BENSET.REQTYPE,1,BENSET.POLICYCODE,0)  
LEFT JOIN IM_PLANS PLA ON PLA.PLAN_CODE=BENSET.PLANCODE  
LEFT JOIN IM_CATEGORIES CAT ON CAT.CATEGORY_CODE=BENSET.CATEGORYCODE  
LEFT JOIN IM_BENEFIT_CODES BEN ON BEN.BENEFIT_CODE=BENSET.BENEFITCODE  
LEFT JOIN GENCONSTANT GEN ON GEN.CONSTANTVALUE=BENSET.APPLICABLEFOR AND GEN.CATEGORY='APPLICABLE' AND
Upper(GEN.LANGUAGECODE)='EN-US' 
LEFT JOIN GENCONSTANT GEN1 ON GEN1.CONSTANTVALUE=BENSET.PROVIDERTYPE AND GEN1.CATEGORY='PROVIDERTYPE' AND 
Upper(GEN1.LANGUAGECODE)='EN-US' 
LEFT JOIN GENCONSTANT GEN2 ON GEN2.CONSTANTVALUE=BENSET.DEDECTABLETYPE AND GEN2.CATEGORY='CALCMETHOD' AND 
Upper(GEN2.LANGUAGECODE)='EN-US' 
LEFT JOIN GENCONSTANT GEN3 ON GEN3.CONSTANTVALUE=BENSET.LIMITTYPE AND GEN3.CATEGORY='CALCMETHOD' AND 
Upper(GEN3.LANGUAGECODE)='EN-US' 
LEFT JOIN GENCONSTANT GEN4 ON GEN4.CONSTANTVALUE=BENSET.CO_IN_TYPE AND GEN4.CATEGORY='CALCMETHOD' AND 
Upper(GEN4.LANGUAGECODE)='EN-US' 
LEFT JOIN GENCONSTANT GEN5 ON GEN5.CONSTANTVALUE=BENSET.PERIODTYPE AND GEN5.CATEGORY='PERIODTYPE' AND 
Upper(GEN5.LANGUAGECODE)='EN-US' 
LEFT JOIN ADMLOOKUPDETAIL LOK1 ON LOK1.LOOKUPDETAILCODE =BENSET.ROOMTYPE  
LEFT JOIN GENCONSTANT GEN7 ON GEN7.CONSTANTVALUE=BENSET.OONCO_IN_TYPE AND GEN7.CATEGORY='CALCMETHOD' AND 
Upper(GEN7.LANGUAGECODE)='EN-US' 
LEFT JOIN GENCONSTANT GEN8 ON GEN8.CONSTANTVALUE=BENSET.OONDEDECTABLETYPE AND GEN8.CATEGORY='CALCMETHOD' AND 
Upper(GEN8.LANGUAGECODE)='EN-US' 
LEFT JOIN GENCONSTANT GENN1 ON GENN1.CONSTANTVALUE=BENSET.EMGDETECTWINETWTYPE AND GENN1.CATEGORY='CALCMETHOD' AND 
Upper(GENN1.LANGUAGECODE)='EN-US' 
LEFT JOIN GENCONSTANT GENN2 ON GENN2.CONSTANTVALUE=BENSET.EMGDETECTOONETWTYPE AND GENN2.CATEGORY='CALCMETHOD' AND 
Upper(GENN2.LANGUAGECODE)='EN-US'  
LEFT JOIN GENCONSTANT GENM1 ON GENM1.CONSTANTVALUE=BENSET.WNSLTYPE AND GENM1.CATEGORY='CALCMETHOD' AND 
Upper(GENM1.LANGUAGECODE)='EN-US'   
LEFT JOIN GENCONSTANT GENM2 ON GENM2.CONSTANTVALUE=BENSET.ONSLTYPE AND GENM2.CATEGORY='CALCMETHOD' AND 
Upper(GENM2.LANGUAGECODE)='EN-US'  
WHERE BENSET.POLICYCODE=100000000000020933 AND BENSET.BENEFITCODE=10000000000000003
AND BENSET.CATEGORYCODE=100000000000000016 AND BENSET.REQTYPE=0


Detail :

SELECT IBA.*,GEN.CONSTANTNAME GENDERNAME,GEN1.CONSTANTNAME APPLICABLEFORNAME FROM IM_BENSETTINGAGELIMITS IBA   
LEFT JOIN GENCONSTANT GEN1 ON GEN1.CONSTANTVALUE=IBA.APPLICABLEFOR AND GEN1.CATEGORY='MARITAL_STATUS' AND 
Upper(GEN1.LANGUAGECODE)='EN-US' 
LEFT JOIN GENCONSTANT GEN ON GEN.CONSTANTVALUE=IBA.GENDERCODE AND GEN.CATEGORY='GENDER' AND 
Upper(GEN.LANGUAGECODE)='EN-US' WHERE IBA.BENEFITSETTINGCODE=100000000000656573


Sub Detail :

SELECT IBR.*,GEN1.CONSTANTNAME RELATIONTYPENAME FROM IM_BENSETTAGERELATION IBR  
LEFT JOIN GENCONSTANT GEN1 ON GEN1.CONSTANTVALUE=IBR.RELATIONTYPECODE AND GEN1.CATEGORY='MEMBERRELATION' AND 
Upper(GEN1.LANGUAGECODE)='EN-US' WHERE IBR.BENSETTLMITAGECODE=1