SELECT IC.*,GEN.CONSTANTNAME EMIRATENAME FROM IM_CATEGORIES IC 
LEFT JOIN GENCONSTANT GEN ON GEN.CATEGORY='MEMBERLOCATION' AND GEN.CONSTANTVALUE=IC.EMIRATE AND GEN.LANGUAGECODE='en-US'
ORDER BY IC.CATEGORY_CODE DESC