Master :

SELECT POLICYCODE,
POLICYNUMBER,
POLICYNAME,
STARTDATE,
ENDDATE,
POLICYFROMDATE,
POLICYPERIOD,
REPORTSTARTDATE,
REPORTENDDATE,
REPORTPRODUCTIONDATE,
SUBREPORT0,
OUTSTANDINGAMOUNT,
IBNRAMOUNT,
PAIDAMOUNT
FROM IM_CLAIMREPORT_DATA WHERE
POLICYCODE = :POLICYCODE;

Sub Report :

SELECT * FROM TABLE(SF_CLAIMCENSUSBEGIN_SR0());
SELECT * FROM TABLE(SF_CLAIMCENSUSENDREPORT_SR1());
SELECT * FROM TABLE(SF_CLAIMDATAMEMBERTYPE_SR2());
SELECT * FROM TABLE(SF_CLAIMDATAMEMBERCOUNT_SR4());
SELECT * FROM TABLE(SF_CLAIMDATADIAGNOSISVALUE_SR9());
SELECT * FROM TABLE(SF_CLAIMDATADIAGNOSISNUM_SR10());
SELECT * FROM TABLE(SF_CLAIMDATAPROVIDERVALUE_SR3());
SELECT * FROM TABLE(SF_CLAIMDATAPROVIDERNUMBER_SR5());
SELECT * FROM TABLE(SF_CLAIMDATANETWORKVALUE_SR6());
SELECT * FROM TABLE(SF_CLAIMDATANETWORKNUMBER_SR7());
SELECT * FROM TABLE(SF_CLAIMDATANETWORKNUMBER_SR8());
SELECT * FROM TABLE(SF_CLAIMPAIDPERSERVICE_SR11());


:POLICYCODE
SELECT POLICYID,POLICYNAME,POLICYCODE FROM IM_POLICY;