SELECT
GENCUR.CURRENCYNAME CURENCY ,
CPH.ENCOUNTER_START_DATE ADMISSIONDATE ,
DECODE(CPH.REQUEST_TYPE , 4,'THIRD PARTY',IMM.APOLICYNAME) POLICYNAME ,
DECODE(CPH.REQUEST_TYPE , 4,'THIRD PARTY',IMM.APOLICYID) POLICYNUMBER ,
GEN2.CONSTANTNAME PROVIDERTYPE ,
DECODE(CPH.REQUEST_TYPE , 4,'THIRD PARTY',PRO.PROVIDERNAME) PROVIDERNAME ,
CPH.INVOICENUMBER INVOICEX,
NVL(IMM.A_STAFF_ID,'0') STAFFNUMBER ,
DECODE(CPH.REQUEST_TYPE , 4,'THIRD PARTY',IMM.AMEMBERNAME) PATIENTNAME ,
DECODE(CPH.REQUEST_TYPE , 4,'THIRD PARTY',NVL(IMM.A_CARDID,CPH.CARDNO))  CARDNUMBER ,  
DECODE(CPH.CLAIM_STATUS,2,CPH.APPROVED_AMOUNT,CPH.REQUEST_AMOUNT) CLAIM_AMOUNT,
NVL((SELECT SUM(DENIEDAMOUNT) DENIEDAMOUNT FROM IM_CLAIM_PROCESS_DETAIL_DTL D WHERE  D.DENIEDFOR=2  AND D.ACTIVITY_DETAIL_CODE IN 
(SELECT ACTIVITY_DETAIL_CODE FROM IM_CLAIM_PROCESS_DETAIL DTL WHERE  DTL.CLAIM_CODE = CPH.CLAIM_CODE ) ),0) DENIED,
CPH.DISCOUNTTOTAL DISCOUNT ,
PRO.PROVIDERID PROVIDER ,
APPROVED_DATE SETTLEDDATE ,
CPH.LASTMODIFIEDON  PROCESSEDDATE ,
APPROVED_DATE POVALIDATIONDATE,
GC.CATEGORY_NAME PRODUCTCLASS ,
IMM.A_FIRST_NAME PRINCIPALFRISTNAME ,
IMM.A_LAST_NAME PRINCIPALFAMILYNAME ,
IMM.ADATE_OF_BIRTH DOB ,
GEN4.CONSTANTNAME NATIONALITY ,
GEN6.CONSTANTNAME DEPENDENCY ,
NVL(GEN7.CONSTANTNAME ,(SELECT  MAX(GEN.CONSTANTNAME) FROM GENCONSTANT  GEN  WHERE GEN.CATEGORY='GENDER' AND GEN.LANGUAGECODE='EN-US'  AND GEN.CONSTANTVALUE IN (SELECT MEM.GENDER FROM IM_MEMBERS MEM WHERE MEM.MEMBER_CODE=CPH.MEMBER_CODE))) AS GENDER,
NVL(GEN8.CONSTANTNAME,(SELECT  MAX(GEN.CONSTANTNAME) FROM GENCONSTANT  GEN  WHERE GEN.CATEGORY='MARITAL_STATUS' AND GEN.LANGUAGECODE='EN-US'  AND GEN.CONSTANTVALUE IN (SELECT MEM.MARITAL_STATUS FROM IM_MEMBERS MEM WHERE MEM.MEMBER_CODE=CPH.MEMBER_CODE))) MARITAL_STATUS,
IMM.MEMBERSTARTDATE POLICYINCEPTIONDATE ,                      
NVL(IMM.MEMBERENDDATE,IMM.POLICYENDDDATE) EXPIRYDATE,
NVL(CPH.ENCOUNTER_END_DATE,CPH.ENCOUNTER_START_DATE) TREATEMENT_END_DATE,
BEN.BENEFITNAME,
BEN.BENEFITID,
(SELECT LISTAGG (IMVD.SHORTDESC, ',') WITHIN GROUP (ORDER BY IMVD.SHORTDESC) FROM IM_CLAIM_PROCESS_DETAIL DTL
LEFT JOIN IM_ACTIVITY_TYPES  ACTTYP ON ACTTYP.TYPECODE=DTL.ACTIVITY_CODE
JOIN IM_VERSION_DETALIS IMVD ON IMVD.DETAILCODE = DTL.VERSIONDETAILCODE
WHERE ACTTYP.VALUE = -1 AND DTL.CLAIM_CODE = CPH.CLAIM_CODE AND DTL.TYPE = 1 GROUP BY DTL.CLAIM_CODE ) ICDCODES,
GEN3.CONSTANTNAME STATUS
FROM IM_CLAIM_PROCESS_HEADER CPH
LEFT JOIN VW_IM_CLAIM_PROCESS_DETAIL_BEN BEN ON BEN.CLAIM_CODE=CPH.CLAIM_CODE  
LEFT  JOIN IM_MEMBERPOLICY IMM ON IMM.MEMBERPOLICYCODE = CPH.MEMBERPOLICYCODE
LEFT JOIN IM_PROVIDERS PRO ON PRO.PROVIDERCODE=CPH.PROVIDER_CODE
LEFT JOIN GENCONSTANT GEN2 ON GEN2.CATEGORY='PROVIDERTYPE' AND GEN2.CONSTANTVALUE=PRO.PROVIDERTYPE AND Upper(GEN2.LANGUAGECODE)='EN-US'
LEFT JOIN GENCONSTANT GEN ON GEN.CATEGORY='AUTHORIZEDSTATUS' AND Upper(GEN.LANGUAGECODE)='EN-US' AND GEN.CONSTANTVALUE=CPH.AUTHORIZEDSTATUS
LEFT JOIN GENCONSTANT GEN3 ON GEN3.CATEGORY='CLAIMREQSTATUS' AND Upper(GEN3.LANGUAGECODE)='EN-US' AND GEN3.CONSTANTVALUE=CPH.CLAIM_STATUS
LEFT JOIN GENCONSTANT GEN5 ON   GEN5.CATEGORY='CLAIMPROSOURCETYPE' AND Upper(GEN5.LANGUAGECODE)='EN-US'  AND GEN5.CONSTANTVALUE=CPH.REQUEST_TYPE
LEFT JOIN GENCONSTANT GEN4 ON   GEN4.CATEGORY='FND_NATIONALITY' AND Upper(GEN4.LANGUAGECODE)='EN-US'  AND GEN4.CONSTANTVALUE=IMM.A_NATIONALITY
LEFT JOIN GENCONSTANT GEN6 ON   GEN6.CATEGORY='RELATIONS' AND Upper(GEN6.LANGUAGECODE)='EN-US'  AND GEN6.CONSTANTVALUE=IMM.ARELATION
LEFT JOIN GENCONSTANT GEN7 ON   GEN7.CATEGORY='GENDER' AND Upper(GEN7.LANGUAGECODE)='EN-US'  AND GEN7.CONSTANTVALUE=IMM.AGENDER
LEFT JOIN GENCONSTANT GEN8 ON   GEN8.CATEGORY='MARITAL_STATUS' AND Upper(GEN8.LANGUAGECODE)='EN-US'  AND GEN8.CONSTANTVALUE=IMM.AMARITAL_STATUS
LEFT JOIN IM_CATEGORIES GC ON GC.CATEGORY_CODE=CPH.CATEGORY_CODE        
LEFT JOIN GENCURRENCY GENCUR ON GENCUR.CURRENCYCODE = NVL(CPH.CURRENCYCODE,100000000000000001)
LEFT JOIN ADMUSER ADM ON ADM.USERCODE = CPH.LASTMODIFIEDBY
WHERE CPH.POLICYCODE = :P_POLICYCODE
AND CPH.TRANSACTIONDATE BETWEEN :SDATE AND :EDATE;