SELECT * FROM(SELECT SUBSTR (IMCOP.CARDNO, 0, 4) || '/' || SUBSTR (IMCOP.CARDNO, 9, 13) POLICYNO_MEMBERNO,
 IMP.AMEMBERNAME MEMBERNAME,NVL (CPH.CPNO, 0) CLAIMNO,  CPH.ACR_FORM_NO FORMNO,(  SELECT LISTAGG (IMVD.SHORTDESC, ',')
 WITHIN GROUP (ORDER BY IMVD.SHORTDESC) FROM IM_CLAIM_PROCESS_DETAIL DTL
 LEFT JOIN IM_ACTIVITY_TYPES ACTTYP ON ACTTYP.TYPECODE = DTL.ACTIVITY_CODE JOIN IM_VERSION_DETALIS IMVD ON IMVD.DETAILCODE = DTL.VERSIONDETAILCODE
 WHERE ACTTYP.VALUE = -1 AND DTL.CLAIM_CODE = CPH.CLAIM_CODE GROUP BY DTL.CLAIM_CODE) ICDCODES,
  (SELECT LISTAGG (ICD.GROUPNAME, ',')
 WITHIN GROUP (ORDER BY ICD.GROUPNAME) FROM IM_CLAIM_PROCESS_DETAIL DTL
 LEFT JOIN IM_ACTIVITY_TYPES ACTTYP ON ACTTYP.TYPECODE = DTL.ACTIVITY_CODE JOIN IM_VERSION_DETALIS IMVD ON IMVD.DETAILCODE = DTL.VERSIONDETAILCODE
 JOIN IM_ICDGROUPING ICD ON ICD.CODE = IMVD.CODE
 WHERE ACTTYP.VALUE = -1 AND DTL.CLAIM_CODE = CPH.CLAIM_CODE GROUP BY DTL.CLAIM_CODE) DIAGNOSISGENERALIZED,TO_CHAR(CPH.ENCOUNTER_START_DATE) TREATMENTSTARTDATE,
 TO_CHAR(CPH.ENCOUNTER_END_DATE) TREATMENTENDDATE, TO_CHAR(IMP.ADATE_OF_BIRTH) DATEOFBIRTH,TRUNC (MONTHS_BETWEEN (SYSDATE, IMP.ADATE_OF_BIRTH) / 12) AGE,
 IMP.RNAME RELATION,IMP.GNAME GENDER,PRO.PROVIDERID HNMCODE,IMC.NAME PHYSCODE,CPH.INVOICENUMBER INVOICENO,
 (SELECT LISTAGG (IBC.BENEFIT_ID, ',')  WITHIN GROUP (ORDER BY IBC.BENEFIT_ID) FROM    IM_CLAIM_PROCESS_DETAIL DTL JOIN IM_BENEFIT_CODES IBC ON
 IBC.BENEFIT_CODE = DTL.BENEFIT_CODE  WHERE DTL.CLAIM_CODE = CPH.CLAIM_CODE AND (:P_BENEFIT_CODE = 1 OR DTL.BENEFIT_CODE = :P_BENEFIT_CODE)
 GROUP BY DTL.CLAIM_CODE) BENEFITTYPES,
 (SELECT LISTAGG (IMVD.SHORTDESC, ',') WITHIN GROUP (ORDER BY IMVD.SHORTDESC) FROM IM_CLAIM_PROCESS_DETAIL_DTL SDTL JOIN IM_CLAIM_PROCESS_DETAIL DTL
 ON DTL.ACTIVITY_DETAIL_CODE = SDTL.ACTIVITY_DETAIL_CODE AND SDTL.DENIEDFOR = 0 JOIN IM_VERSION_DETALIS IMVD
 ON IMVD.DETAILCODE = SDTL.DENIAL_REASON WHERE DTL.CLAIM_CODE = CPH.CLAIM_CODE GROUP BY DTL.CLAIM_CODE ) DECLINECODE,
 (SELECT SUM(DTL.DECLINEAMOUNT) FROM IM_CLAIMREGISTERDTL_VW DTL WHERE DTL.CLAIM_CODE = CPH.CLAIM_CODE AND (:P_BENEFIT_CODE = 1 OR DTL.BENEFIT_CODE = :P_BENEFIT_CODE))  DECLINEAMOUNT,
 (SELECT LISTAGG (IMVD.SHORTDESC, ',') WITHIN GROUP (ORDER BY IMVD.SHORTDESC) FROM IM_CLAIM_PROCESS_DETAIL_DTL SDTL JOIN IM_CLAIM_PROCESS_DETAIL DTL
 ON DTL.ACTIVITY_DETAIL_CODE = SDTL.ACTIVITY_DETAIL_CODE AND SDTL.DENIEDFOR = 2 JOIN IM_VERSION_DETALIS IMVD
 ON IMVD.DETAILCODE = SDTL.DENIAL_REASON WHERE DTL.CLAIM_CODE = CPH.CLAIM_CODE GROUP BY DTL.CLAIM_CODE ) RECOVERYCODE,
 (SELECT SUM(DTL.RECOVERYAMOUNT) FROM IM_CLAIMREGISTERDTL_VW DTL WHERE DTL.CLAIM_CODE = CPH.CLAIM_CODE AND (:P_BENEFIT_CODE = 1 OR DTL.BENEFIT_CODE = :P_BENEFIT_CODE))  RECOVERYAMOUNT,
 (SELECT SUM(DTL.PAYABLEAMOUNT) FROM IM_CLAIMREGISTERDTL_VW DTL WHERE DTL.CLAIM_CODE = CPH.CLAIM_CODE AND (:P_BENEFIT_CODE = 1 OR DTL.BENEFIT_CODE = :P_BENEFIT_CODE))PAYABLEAMOUNT  FROM IM_CLAIM_PROCESS_HEADER CPH
 JOIN IM_MEMBERS_MAT_VW IMP ON IMP.MEMBERPOLICYCODE = CPH.MEMBERPOLICYCODE
 JOIN IM_PROVIDERS PRO ON PRO.PROVIDERCODE = CPH.PROVIDER_CODE
 JOIN IM_CORDPRINT IMCOP ON IMCOP.MEMBERCODE = IMP.MEMBERCODE AND IMCOP.POLICYCODE = IMP.POLICYCODE AND IMCOP.CATEGORYCODE = IMP.CATEGORYCODE
 JOIN IM_CLINICIANS IMC ON IMC.CDCODE = CPH.CDCODE
 LEFT JOIN GENCONSTANT  IGEN ON IGEN.CONSTANTVALUE=NVL(IMC.SPECIALTY,310) AND IGEN.CATEGORY='SPECIALTY' AND  UPPER(IGEN.LANGUAGECODE)='EN-US'
 WHERE CPH.CLAIM_STATUS <> 1  
AND CPH.PROVIDER_CODE = Nvl(:P_PROVIDERCODE,CPH.PROVIDER_CODE) AND
CPH.MEMBER_CODE  = Nvl(:P_MEMBERIDCODE,CPH.MEMBER_CODE) AND
(CPH.POLICYCODE = Nvl(:POLICY_CODE,CPH.POLICYCODE) OR CPH.POLICYCODE = Nvl(:P_INDPOLICYCODE,CPH.POLICYCODE))  
AND IMP.AGENDER = Nvl(:P_GCODE,IMP.AGENDER) AND CPH.TREATMENT_TYPE = Nvl(:P_TYPECODE,CPH.TREATMENT_TYPE) AND 
IMC.SPECIALTY = Nvl(:P_SPECIALCODE,IMC.SPECIALTY) 
AND  CPH.ENCOUNTER_START_DATE BETWEEN Nvl(:P_TSDATE,SYSDATE-1000) AND Nvl(:P_TSDATE,SYSDATE)
AND CPH.TRANSACTIONDATE BETWEEN Nvl(:P_SDATE,SYSDATE-1000) AND Nvl(:P_SDATE,SYSDATE)) CPH
