SELECT * FROM(SELECT SUBSTR(POL.POLICYID,0,4) PRODUCT, SUBSTR(POL.POLICYID,6,6) SERIALNO,
SUBSTR (IMCOP.CARDNO, 0, 4) || '/' || SUBSTR (IMCOP.CARDNO, 9, 13) POLICYNO_MEMBERNO,CPH.ACR_FORM_NO FORMNO,
IMP.AMEMBERNAME MEMBERNAME,NVL (CPH.CPNO, 0) CLAIMNO,(  SELECT LISTAGG (IMVD.SHORTDESC, ',')
WITHIN GROUP (ORDER BY IMVD.SHORTDESC) FROM IM_CLAIM_PROCESS_DETAIL DTL
LEFT JOIN IM_ACTIVITY_TYPES ACTTYP ON ACTTYP.TYPECODE = DTL.ACTIVITY_CODE JOIN IM_VERSION_DETALIS IMVD ON IMVD.DETAILCODE = DTL.VERSIONDETAILCODE
WHERE ACTTYP.VALUE = -1 AND DTL.CLAIM_CODE = CPH.CLAIM_CODE GROUP BY DTL.CLAIM_CODE) ICDCODES,
 (SELECT LISTAGG (TO_CHAR(ICD.GROUPNAME), ',')
 WITHIN GROUP (ORDER BY TO_CHAR(ICD.GROUPNAME)) FROM IM_CLAIM_PROCESS_DETAIL DTL
 LEFT JOIN IM_ACTIVITY_TYPES ACTTYP ON ACTTYP.TYPECODE = DTL.ACTIVITY_CODE JOIN IM_VERSION_DETALIS IMVD ON IMVD.DETAILCODE = DTL.VERSIONDETAILCODE
 JOIN IM_ICDGROUPING ICD ON ICD.CODE = IMVD.CODE
 WHERE ACTTYP.VALUE = -1 AND DTL.CLAIM_CODE = CPH.CLAIM_CODE GROUP BY DTL.CLAIM_CODE) DIAGNOSISGENERALIZED,TO_CHAR(CPH.ENCOUNTER_START_DATE) TREATMENTSTARTDATE,
TO_CHAR(CPH.ENCOUNTER_END_DATE) TREATMENTENDDATE, TO_CHAR(IMP.ADATE_OF_BIRTH) DATEOFBIRTH,TRUNC (MONTHS_BETWEEN (SYSDATE, IMP.ADATE_OF_BIRTH) / 12) AGE,
IMP.RNAME RELATION,PRO.PROVIDERID HNMCODE,IMC.NAME PHYSCODE,CPH.INVOICENUMBER INVOICENO,IBC.BENEFIT_ID,IVD.CODE CPTCODE,
DTL.REQUESTAMOUNT,DTL.DEDUCTIBLE_AMOUNT,DTL.COINSURANCE_AMOUNT,NVL((SELECT SUM(DENIEDAMOUNT) FROM IM_RECOVERYAMOUNT_VW DEC WHERE DEC.ACTIVITY_DETAIL_CODE = DTL.ACTIVITY_DETAIL_CODE),0) HNMAMOUNT
,NVL((SELECT SUM(DENIEDAMOUNT) FROM IM_DECLINEAMOUNT_VW DEC WHERE DEC.CLAIM_CODE = CPH.CLAIM_CODE),0) DECLINEAMOUNT,DTL.TOTAL PAYABLEAMOUNT,IVDD.CODE DECLINECODE
FROM IM_CLAIM_PROCESS_HEADER CPH
LEFT JOIN IM_CLAIM_PROCESS_DETAIL DTL ON DTL.CLAIM_CODE = CPH.CLAIM_CODE AND NVL(DTL.TYPE,0) = 0
LEFT JOIN IM_VERSION_DETALIS IVD ON IVD.DETAILCODE = DTL.VERSIONDETAILCODE
LEFT JOIN IM_VERSION_DETALIS IVDD ON IVDD.DETAILCODE = DTL.DENIAL_REASON
LEFT JOIN IM_BENEFIT_CODES IBC ON IBC.BENEFIT_CODE = DTL.BENEFIT_CODE
JOIN IM_MEMBERS_MAT_VW IMP ON IMP.MEMBERPOLICYCODE = CPH.MEMBERPOLICYCODE  JOIN IM_PROVIDERS PRO ON PRO.PROVIDERCODE = CPH.PROVIDER_CODE
JOIN IM_CORDPRINT IMCOP ON IMCOP.MEMBERCODE = IMP.MEMBERCODE AND IMCOP.POLICYCODE = IMP.POLICYCODE AND IMCOP.CATEGORYCODE = IMP.CATEGORYCODE
JOIN IM_CLINICIANS IMC ON IMC.CDCODE = CPH.CDCODE
LEFT JOIN IM_POLICY POL ON POL.POLICYCODE = IMP.POLICYCODE AND IMP.TYPEE = 1
LEFT JOIN IM_INDIVIDUALPOLICY IPOL ON IPOL.INDIVIDUALPOLICYCODE = IMP.POLICYCODE AND IMP.TYPEE = 2
LEFT JOIN GENCONSTANT  IGEN ON IGEN.CONSTANTVALUE=NVL(IMC.SPECIALTY,310) AND IGEN.CATEGORY='SPECIALTY' AND  UPPER(IGEN.LANGUAGECODE)='EN-US'
WHERE CPH.CLAIM_STATUS <> 1  
AND CPH.PROVIDER_CODE = Nvl(:P_PROVIDERCODE,CPH.PROVIDER_CODE) AND
CPH.MEMBER_CODE  = Nvl(:P_MEMBERIDCODE,CPH.MEMBER_CODE) AND
(CPH.POLICYCODE = Nvl(:POLICY_CODE,CPH.POLICYCODE) OR CPH.POLICYCODE = Nvl(:P_INDPOLICYCODE,CPH.POLICYCODE))  
AND IMP.AGENDER = Nvl(:P_GCODE,IMP.AGENDER) AND CPH.TREATMENT_TYPE = Nvl(:P_TYPECODE,CPH.TREATMENT_TYPE) AND 
IMC.SPECIALTY = Nvl(:P_SPECIALCODE,IMC.SPECIALTY) 
AND  CPH.ENCOUNTER_START_DATE BETWEEN Nvl(:P_TSDATE,SYSDATE-1000) AND Nvl(:P_TSDATE,SYSDATE)
AND CPH.TRANSACTIONDATE BETWEEN Nvl(:P_SDATE,SYSDATE-1000) AND Nvl(:P_SDATE,SYSDATE))
