SELECT IPTD.PROVIDERINTERNALCODE Code,IPTD.PROVIDERINTERNALDESC Description,IPTD.NETVALUE Price  
FROM IM_PROVIDERS PRO  
JOIN (SELECT PROVIDERCODE,TARIFFCODE FROM IM_PROVIDER_TARIFF WHERE PROVIDERCODE=  ProviderCode  ) IPT ON IPT.PROVIDERCODE = PRO.PROVIDERCODE  
JOIN (SELECT TARIFFCODE,PROVIDERINTERNALCODE,PROVIDERINTERNALDESC,NETVALUE,EFFECTIVEFROM,EFFECTIVETO FROM IM_PROVIDER_TARIFF_DETAILS) IPTD ON IPTD.TARIFFCODE = IPT.TARIFFCODE  
WHERE PRO.PROVIDERCODE=  :PROVIDERCODE   AND :SDATE  BETWEEN IPTD.EFFECTIVEFROM AND IPTD.EFFECTIVETO;

SELECT * FROM IM_CLAIMHAADDOWNLOADPRICELIST WHERE PROVIDERCODE = :PROVIDERCODE;   