POLICY ENDORESMENT:
SELECT * FROM TABLE(SF_POLICYADDDEL('EN-US',:PRIMKEY));

CREDIT/DEBIT POLICY ENDORESMENT:
SELECT * FROM TABLE(SF_POLICYCREDITDEBITLIST('EN-US',:PRIMKEY,:P_USERCODE));

SELECT JVPOSTINGCODE POLICYFINANCEPOSTINGCODE,INSTALLMENTNO,INSTALLMENTDATE,PERCENTAGE,AMOUNT FROM IM_NGI_JV_INSTALLMENT
WHERE JVPOSTINGCODE IN (SELECT JVPOSTINGCODE FROM IM_NGI_JVPOSTING WHERE MEMOTYPE = 1)  ORDER BY INSTALLMENTNO ASC;


POLICY MEMBER DETAIL LIST:
SELECT * FROM TABLE(SF_ENDORSEMENTPOSTINGDTL('EN-US',:PRIMKEY));

