SELECT BIL.* FROM(SELECT BIL.*,ADM.USERNAME CREATEDUSERNAME,ADM1.USERNAME MODIFIEDUSERNAME,GEN.CONSTANTNAME AS 
AUTHORIZEDSTATUSNAME,  CON.COUNTRYNAME COUNTRYNAME,PLACE.PLACENAME CITYNAME,STATE.PROVINCENAME STATENAME,
BANK.CONSTANTNAME BANKNAME,GEC.CURRENCYNAME CURRENCYNAME FROM IM_GENERAL_COMM_BILLING_DETAIL BIL   
JOIN ADMCOMPANY ADMCOM ON ADMCOM.COMPANYCODE=BIL.COMPANYCODE AND ADMCOM.COMPANYCODE= 1 
JOIN (SELECT CONSTANTVALUE,CONSTANTNAME FROM GENCONSTANT WHERE CATEGORY='AUTHORIZEDSTATUS' AND LANGUAGECODE='en-US')GEN ON
GEN.CONSTANTVALUE=BIL.AUTHORIZEDSTATUS   
LEFT JOIN GENCOUNTRY CON ON CON.COUNTRYCODE=BIL.COUNTRYCODE  
LEFT JOIN GENPLACE PLACE ON PLACE.PLACECODE=BIL.CITYCODE  
LEFT JOIN GENCONSTANT BANK ON BANK.CONSTANTVALUE=BIL.BANKCODE AND CATEGORY='SP_BANKS' AND LANGUAGECODE='en-US'  
LEFT JOIN GENPROVINCE STATE ON STATE.PROVINCECODE=BIL.STATECODE  
JOIN ADMUSER ADM ON ADM.USERCODE=BIL.CREATEDBY  
JOIN ADMUSER ADM1 ON ADM1.USERCODE=BIL.LASTMODIFIEDBY  
LEFT JOIN GENCURRENCY GEC ON GEC.CURRENCYCODE=BIL.CURRENCYCODE ORDER BY GENERALCOMMBILLINGCODE DESC)BIL