HNM Posting Master :

SELECT HPP.*,GEN.CONSTANTNAME POLICYTYPENAME,POL.POLICYID,POL.POLICYNAME,POL.STARTDATE,POL.ENDDATE,  
IPOL.POLICYID IPPOLICYID,GEN1.CONSTANTNAME AUTHORIZEDSTATUSNAME,IPOL.POLICYNAME INDIVIDUALPOLICYNAME,
PRO.PROVIDERNAME,
(SELECT SUM(AMOUNT) FROM IM_HNM_PROVIDERPAYMENTDTLS WHERE PROVIDERPAYMENTCODE=HPP.PROVIDERPAYMENTCODE)TOTAL 
FROM IM_HNMPROVIDERPAYMENT  HPP   
LEFT JOIN GENCONSTANT GEN ON GEN.CONSTANTVALUE=HPP.POLICYTYPECODE AND GEN.CATEGORY='MEMBERPOLICYTYPE' AND 
UPPER(GEN.LANGUAGECODE)='EN-US'   
LEFT JOIN (SELECT PL.POLICYCODE POLICYCODE, PL.POLICYID,PL.POLICYNAME,PL.STARTDATE,PL.ENDDATE, 1 TYPECODE  
FROM IM_POLICY PL 
UNION ALL   
SELECT IPOL.INDIVIDUALPOLICYCODE POLICYCODE,IPOL.POLICYID,IPOL.POLICYNAME,IPOL.STARTDATE,IPOL.ENDDATE,2 TYPECODE 
FROM IM_INDIVIDUALPOLICY  IPOL) POL ON   
POL.POLICYCODE=DECODE(HPP.POLICYTYPECODE,1,HPP.POLICYCODE,2,HPP.INDIVIDUALPOLICYCODE)AND POL.TYPECODE=HPP.POLICYTYPECODE  
LEFT JOIN IM_INDIVIDUALPOLICY IPOL ON IPOL.INDIVIDUALPOLICYCODE= HPP.INDIVIDUALPOLICYCODE   
LEFT JOIN IM_PROVIDERS PRO ON PRO.PROVIDERCODE=HPP.PROVIDERCODE    
LEFT JOIN IM_POLICY PP ON PP.POLICYCODE=HPP.POLICYCODE   
LEFT JOIN GENCONSTANT GEN1 ON GEN1.CONSTANTVALUE=HPP.AUTHORIZEDSTATUS AND GEN1.CATEGORY='AUTHORIZEDSTATUS' AND 
UPPER(GEN1.LANGUAGECODE)='EN-US' 


HNM Provider Detail :

SELECT DET.* FROM IM_HNM_PROVIDERPAYMENTDTLS DET WHERE DET.PROVIDERPAYMENTCODE=100000000000005054



HNM Provider Exclude Detail :

SELECT DET.* FROM IM_HNM_PROVIDERPAYMENT_EXC DET WHERE DET.PROVIDERPAYMENTCODE=100000000000005054


Call the below function after save :

IM_FINANCE_POSTING.IM_HNM_PROVIDER_PAYMENT_FN(P_PRIMKEY NUMBER,PROVIDERCODE NUMBER)