 SELECT
IMPOL.TYPEE  POLICYTYPE,
HDR.POLICYCODE,
(IMPOL.APOLICYID) POLICYID,
(IMPOL.APOLICYNAME) POLICYNAME,
--POL.POLICYNO,
HDR.CARDNO,
INITCAP(IMPOL.AMEMBERNAME) INSUREDPERSON,
HDR.ENCOUNTER_START_DATE TREATMENTDATE,
HDR.LASTMODIFIEDON INVOICEDATE,
HDR.INVOICENUMBER,
HDR.REQUEST_AMOUNT INVOICEAMOUNT,
NVL(HDR.DENAILVALUE,0) -  NVL((SELECT SUM(DENIEDAMOUNT) FROM IM_DECLINEAMOUNT_VW DEC WHERE DEC.CLAIM_CODE = HDR.CLAIM_CODE),0) RECOVERYAMOUNT,
NVL(HDR.DEDUCTABLEVALUE,0) DEDUCTIBLEAMOUNT,
NVL(HDR.CO_INS_VALUE,0) COINSURANCEAMOUNT,
--(NVL(HDR.APPROVED_AMOUNT,0) + NVL((SELECT SUM(DENIEDAMOUNT) FROM IM_DECLINEAMOUNT_VW DEC WHERE DEC.CLAIM_CODE = HDR.CLAIM_CODE),0)) AS NETPAY,
(NVL(HDR.APPROVED_AMOUNT,0) + NVL((SELECT SUM(DENIEDAMOUNT) FROM IM_DECLINEAMOUNT_VW DEC WHERE DEC.CLAIM_CODE = HDR.CLAIM_CODE),0))
-((NVL(HDR.APPROVED_AMOUNT,0) + NVL((SELECT SUM(DENIEDAMOUNT) FROM IM_DECLINEAMOUNT_VW DEC WHERE DEC.CLAIM_CODE = HDR.CLAIM_CODE),0))
 *DECODE(HDR.REQUEST_TYPE,1,0,2,(NVL(DISC.DISCOUNTVALUE,0)/100))) AS NETPAY,
--NVL(HDR.DECLINEAMOUNT,0) HDRDECLINEAMOUNT,
NVL((SELECT SUM(DENIEDAMOUNT) FROM IM_DECLINEAMOUNT_VW DEC WHERE DEC.CLAIM_CODE = HDR.CLAIM_CODE),0)  HDRDECLINEAMOUNT,
NVL(HDR.ACR_FORM_NO,0) FROMNUMBER,
(IMPRO.PROVIDERID|| '-' || IMPRO.PROVIDERNAME) PROVIDERID,IMPRO.PROVIDERNAME,
--HDR.CLAIM_CODE,HDR.POLICYCODE,
HDR.MEMBER_CODE,
--HDR.CATEGORY_CODE,
--POL.BROKERCODE,POL.AGENTCODE,POL.OWNERCODE,
0 GROUP_CODE,
HDR.PROVIDER_CODE,
--SDATE AS FROMDATE,
--EDATE AS TODATE,
((IMC.ORGINALLICENCE||'-'||IMC.NAME)) CLINICIANNAME,
IMC.CDCODE CDCODE,
(SELECT LISTAGG (IMVD.CODE || '-' || IMVD.SHORTDESC, ',') WITHIN GROUP (ORDER BY IMVD.SHORTDESC) FROM IM_CLAIM_PROCESS_DETAIL_DTL SDTL
JOIN IM_VERSION_DETALIS IMVD ON IMVD.DETAILCODE = SDTL.DENIAL_REASON
WHERE DTL.ACTIVITY_DETAIL_CODE = SDTL.ACTIVITY_DETAIL_CODE GROUP BY SDTL.ACTIVITY_DETAIL_CODE) RECOVERYCODE,
HDR.TRANSACTIONDATE TRANSACTIONDATE,
'' ISSERIALNONEEDED,
HDR.CLAIM_CODE,
IVD.CODE CPTCODE,IVD.SHORTDESC DESCRIPTION,NVL(DTL.REQUESTAMOUNT,0) REQAMT,
--(NVL(DTL.TOTAL,0) + NVL((SELECT NVL(DENIEDAMOUNT,0) FROM IM_CLAIM_PROCESS_DETAIL_DTL SDTL  WHERE SDTL.ACTIVITY_DETAIL_CODE = DTL.ACTIVITY_DETAIL_CODE AND SDTL.DENIEDFOR = 0),0))TOTAL
(NVL(DTL.TOTAL,0) + NVL((SELECT NVL(DENIEDAMOUNT,0) FROM IM_CLAIM_PROCESS_DETAIL_DTL SDTL  WHERE
 SDTL.ACTIVITY_DETAIL_CODE = DTL.ACTIVITY_DETAIL_CODE AND SDTL.DENIEDFOR IN (0,3)),0))-
((NVL(DTL.TOTAL,0) + NVL((SELECT NVL(DENIEDAMOUNT,0) FROM IM_CLAIM_PROCESS_DETAIL_DTL SDTL
WHERE SDTL.ACTIVITY_DETAIL_CODE = DTL.ACTIVITY_DETAIL_CODE AND SDTL.DENIEDFOR = 0),0)) *
 DECODE(HDR.REQUEST_TYPE,1,0,2,(NVL(DISC.DISCOUNTVALUE,0)/100)))
TOTAL
,NVL(DTL.COINSURANCE_AMOUNT,0) COINSAMT,
NVL(DTL.DEDUCTIBLE_AMOUNT,0) DEDUCTAMT,(NVL(DTL.DENIAL_VALUE,0) -
NVL((SELECT NVL(DENIEDAMOUNT,0) FROM IM_CLAIM_PROCESS_DETAIL_DTL SDTL  WHERE
 SDTL.ACTIVITY_DETAIL_CODE = DTL.ACTIVITY_DETAIL_CODE AND SDTL.DENIEDFOR IN (0,3)),0)) DENIALAMT,
NVL(DTL.DECLINEAMOUNT,0) AS DECLINEAMOUNT,
(SELECT  SUM(NETTOTAL) FROM IM_DISCPAYMENT_VW WHERE CLAIM_CODE IN
 (SELECT ECT.CLAIMCODE FROM IM_ENDPOSTCLAIMDTL ECT  WHERE ECT.ENDORESMENTCODE = APRIKEY)) NETTOTAL,
(SELECT  SUM(RECOVERYTOTAL) FROM IM_DISCPAYMENT_VW WHERE CLAIM_CODE IN
 (SELECT ECT.CLAIMCODE FROM IM_ENDPOSTCLAIMDTL ECT  WHERE ECT.ENDORESMENTCODE = APRIKEY)) RECOVERYTOTAL,
(SELECT  SUM(DEDUCTIBLETOTAL) FROM IM_DISCPAYMENT_VW WHERE CLAIM_CODE IN
 (SELECT ECT.CLAIMCODE FROM IM_ENDPOSTCLAIMDTL ECT  WHERE ECT.ENDORESMENTCODE = APRIKEY))  DEDUCTIBLETOTAL,
(SELECT  SUM(COINSURANCETOTAL) FROM IM_DISCPAYMENT_VW WHERE CLAIM_CODE IN
 (SELECT ECT.CLAIMCODE FROM IM_ENDPOSTCLAIMDTL ECT  WHERE ECT.ENDORESMENTCODE = APRIKEY))  COINSURANCETOTAL,
 (SELECT  SUM(INVOICETOTAL) FROM IM_DISCPAYMENT_VW WHERE CLAIM_CODE IN
 (SELECT ECT.CLAIMCODE FROM IM_ENDPOSTCLAIMDTL ECT  WHERE ECT.ENDORESMENTCODE = APRIKEY)) INVOICETOTAL
FROM IM_CLAIM_PROCESS_HEADER HDR
JOIN IM_CLAIM_PROCESS_DETAIL DTL ON DTL.CLAIM_CODE = HDR.CLAIM_CODE
LEFT  JOIN IM_VERSION_DETALIS IVD ON IVD.DETAILCODE =DTL.VERSIONDETAILCODE
JOIN IM_MEMBERPOLICY IMPOL ON IMPOL.MEMBERPOLICYCODE = HDR.MEMBERPOLICYCODE
--LEFT JOIN IM_POLICY POL ON POL.POLICYCODE = HDR.POLICYCODE AND IMPOL.TYPEE=1
--LEFT JOIN IM_INDIVIDUALPOLICY IPOL ON IPOL.INDIVIDUALPOLICYCODE = HDR.POLICYCODE AND IMPOL.TYPEE=2
LEFT JOIN IM_PROVIDERS IMPRO ON IMPRO.PROVIDERCODE = HDR.PROVIDER_CODE
--LEFT JOIN IM_PHARMACY_PROVIDER_TARIFF DISC ON DISC.PROVIDERCODE=IMPRO.PROVIDERCODE AND DISC.ENDDATE IS NULL
LEFT JOIN(SELECT DISC.PROVIDERCODE,DISC.DISCOUNTVALUE,DISC.ENDDATE FROM IM_PHARMACY_PROVIDER_TARIFF DISC WHERE  PPTCODE IN (
SELECT MAX(PPTCODE) FROM IM_PHARMACY_PROVIDER_TARIFF GROUP BY PROVIDERCODE) )DISC ON DISC.PROVIDERCODE=IMPRO.PROVIDERCODE AND DISC.ENDDATE IS NULL
LEFT JOIN IM_CLINICIANS IMC ON IMC.CDCODE = HDR.CDCODE
WHERE
HDR.CLAIM_CODE IN (SELECT ECT.CLAIMCODE FROM IM_ENDPOSTCLAIMDTL ECT  WHERE ECT.ENDORESMENTCODE = :APRIKEY)
ORDER BY HDR.TRANSACTIONDATE ASC