SELECT GEN5.CONSTANTNAME PAYMENTNAME,ENDOS.PAYMENTCODE PAYMENTCODE,0 AS SELECTCLAIM,JV.CLAIMREFCODE,
JV.REF_NO DOCUMENTNUMBER,JV.REFDATE,JV.AMOUNT,ENDOS.PROVIDERCODE,PRO.PROVIDERID,PRO.PROVIDERNAME,
JV.JVPOSTINGCODE,JV.COMPANYCODE,PDTL.BENEFICIARYNAME, GENCON.CONSTANTNAME BANKNAME,JV.ACCOUNTNO,
'' FINANCECOMMENTS,  
EC.RAUPLOADDATE,0 SELECTCLAIMS FROM IM_NGI_JVPOSTING JV   
LEFT JOIN IM_ENDORSEMENTPOSTING ENDOS ON ENDOS.ENDORESMENTCODE =JV.CLAIMREFCODE  
LEFT JOIN (SELECT DISTINCT RAUPLOADDATE,PAYMENT_REFERENCE FROM ECLAIMS) EC ON EC.PAYMENT_REFERENCE = JV.REF_NO 
LEFT JOIN  IM_PROVIDERS PRO ON  PRO.PROVIDERCODE=ENDOS.PROVIDERCODE  
LEFT JOIN IM_PROVIDER_BILLING_DETAIL PDTL ON PDTL.PROVIDERCODE=PRO.PROVIDERCODE  
LEFT JOIN GENCONSTANT GEN5 ON GEN5.CONSTANTVALUE=ENDOS.PAYMENTCODE AND GEN5.CATEGORY='PRROVIDERPAYMENT' 
AND GEN5.LANGUAGECODE='EN-US'
LEFT JOIN GENCONSTANT GENCON ON GENCON.CONSTANTVALUE=PDTL.BANKCODE AND GENCON.CATEGORY='SP_BANKS' 
AND GENCON.LANGUAGECODE='EN-US'   
WHERE  ENDOS.PROVIDERCODE IS NOT NULL 
AND NVL(ENDOS.AUTHORIZEDSTATUS,0)<>2 AND 
JV.REFDATE BETWEEN PDTL.STARTDATE AND NVL(PDTL.ENDDATE,JV.REFDATE) AND 
ENDOS.PROVIDERCODE ='1000000000000000979'  AND 
JV.REFDATE BETWEEN TO_DATE('01-03-17','DD/MM/RR') AND TO_DATE('30-04-17','DD/MM/RR') 
ORDER BY JV.REFDATE DESC