SELECT INS.*,GEN.CONSTANTNAME INSURANCETYPENAME,ILOC.ORGANIZATION_NAME BRANCHNAME FROM IM_INSURER INS   
JOIN ADMCOMPANY ADMCOM ON ADMCOM.COMPANYCODE=INS.COMPANYCODE AND ADMCOM.COMPANYCODE=1  
LEFT JOIN HR_ORGANIZATIONS_D ILOC ON ILOC.ORGANIZATIONS_CODE=INS.BRANCHCODE 
LEFT JOIN GENCONSTANT GEN ON GEN.CONSTANTVALUE= INS.INS_TYPE AND GEN.CATEGORY='INSURANCETYPE' AND GEN.LANGUAGECODE='en-US'