MED Finance Master :

SELECT MED.*, GEN1.CONSTANTNAME AUTHORIZEDSTATUSNAME 
FROM IM_MEDFINANCEPOSTING  MED    
LEFT JOIN GENCONSTANT GEN1 ON GEN1.CONSTANTVALUE=MED.AUTHORIZEDSTATUS AND GEN1.CATEGORY='AUTHORIZEDSTATUS' 
AND Upper(GEN1.LANGUAGECODE)='EN-US'   
ORDER BY MED.MEDFINANCEPOSTINGCODE DESC

MED Finance Detail :

SELECT MDTL.* FROM IM_MEDFINANCEPOSTINGDTL MDTL WHERE MDTL.MEDFINANCEPOSTINGCODE=100000000000009727;


Call below function after save :

IM_FINANCE_POSTING.IM_MEDFINANCE_PAYMENT_FN(P_PRIMKEY NUMBER);