Member Master :

SELECT IM.*,(MEM.FIRST_NAME||' '||MEM.LAST_NAME)  PARENTMEMBERNAME,GEN.CONSTANTNAME AS MEMBERTYPENAME,
GEN1.CONSTANTNAME AS GENDERNAME,GEN2.CONSTANTNAME AS RELATIONNAME,GEN3.CONSTANTNAME AS DESIGNATIONNAME,
G4.CONSTANTNAME MARITAL_STATUSNAME, GEN4.CONSTANTNAME AS NATIONALITYNAME,GEN5.CONSTANTNAME AS NATIONALITYDISPLAYNAME,
IG.GROUP_NAME,GC.CATEGORY_NAME CATEGORYNAME, GENC1.CONSTANTNAME AS RESIDENTIALLOCATIONNAME, 
GENC2.CONSTANTNAME AS WORKLOCATIONNAME, GENC3.CONSTANTNAME AS SALARYBANDNAME, GENC4.CONSTANTNAME AS COMMISSIONTYPENAME, 
GENC5.CONSTANTNAME AS ENTITYTYPENAME, GENC6.CONSTANTNAME AS ENTITYIDNAME  ,0 CATEGORYCOUNT,'' VIEWPARENTBTN,
EMI.PROVINCENAME EMIRATENAME,PARGRO.GROUP_NAME AS PARENTGROUPNAME,GEN6.CONSTANTNAME AS STATUSNAME,POL.POLICYID,
POL.POLICYNAME,GEN11.CONSTANTNAME AS LOCATIONNAME,GEE.CONSTANTNAME ENTRYTYPENAME FROM IM_MEMBERS IM 
LEFT JOIN GENCONSTANT  GEN ON GEN.CONSTANTVALUE=IM.MEMBER_TYPE AND GEN.CATEGORY='MEMBERTYPE' AND Upper(GEN.LANGUAGECODE)=Upper('EN-US') 
LEFT JOIN GENCONSTANT GEN1 ON GEN1.CONSTANTVALUE=IM.GENDER AND GEN1.CATEGORY='GENDER' AND Upper(GEN1.LANGUAGECODE)=Upper('EN-US') 
LEFT JOIN GENCONSTANT GEN2 ON GEN2.CONSTANTVALUE=IM.RELATION  AND GEN2.CATEGORY='MEMBERRELATION' AND Upper(GEN2.LANGUAGECODE)=Upper('EN-US') 
LEFT JOIN GENCONSTANT GEN3 ON GEN3.CONSTANTVALUE=IM.DESIGNATION   AND GEN3.CATEGORY='NGIDESIGNATIONS' AND Upper(GEN3.LANGUAGECODE)=Upper('EN-US') 
LEFT JOIN GENCONSTANT GEN4 ON GEN4.CONSTANTVALUE=IM.NATIONALITY  AND GEN4.CATEGORY='FND_NATIONALITY' AND Upper(GEN4.LANGUAGECODE)=Upper('EN-US') 
LEFT JOIN GENCONSTANT GEN5 ON GEN5.CONSTANTVALUE=IM.NATIONALITY_DISPLAY AND GEN5.CATEGORY='NATIONALITY' AND Upper(GEN5.LANGUAGECODE)=Upper('EN-US') 
LEFT JOIN IM_GROUPS IG ON IG.GROUP_CODE=IM.GROUP_CODE 
LEFT JOIN IM_CATEGORIES GC ON GC.CATEGORY_CODE=IM.CATEGORY_CODE  
LEFT JOIN IM_MEMBERS MEM ON MEM.MEMBER_CODE=IM.PARENT_ID  
LEFT  JOIN GENCONSTANT   G4 ON  G4.CATEGORY='MARITAL_STATUS' AND G4.CONSTANTVALUE=IM.MARITAL_STATUS AND Upper(G4.LANGUAGECODE)=Upper('EN-US')  
LEFT JOIN GENPROVINCE EMI ON EMI.PROVINCECODE=IM.EMIRATECODE 
LEFT JOIN IM_GROUPS PARGRO ON PARGRO.GROUP_CODE=IM.PARENTGROUPCODE  
LEFT JOIN GENCONSTANT GEN6 ON GEN6.CONSTANTVALUE=IM.STATUS AND GEN6.CATEGORY='CUSSTATUS' AND Upper(GEN6.LANGUAGECODE)=Upper('EN-US')  
LEFT JOIN IM_POLICY POL ON POL.POLICYCODE=IM.POLICYCODE  
LEFT JOIN GENCONSTANT GEN11 ON GEN11.CATEGORY='MEMBERLOCATION' AND GEN11.CONSTANTVALUE=IM.LOCATION AND Upper(GEN11.LANGUAGECODE)=Upper('EN-US')  
LEFT JOIN GENCONSTANT GEE ON GEE.CONSTANTVALUE=IM.ENTRYTYPE AND GEE.CATEGORY='EMIRATETYPE' AND Upper(GEE.LANGUAGECODE)=Upper('EN-US')  
LEFT JOIN GENCONSTANT GENC1 ON GENC1.CATEGORY='MEMBERLOCATION' AND GENC1.CONSTANTVALUE=IM.RESIDENTLOCATION AND Upper(GENC1.LANGUAGECODE)=Upper('EN-US')  
LEFT JOIN GENCONSTANT GENC2 ON GENC2.CATEGORY='MEMBERLOCATION' AND GENC2.CONSTANTVALUE=IM.WORKLOCATION AND Upper(GENC2.LANGUAGECODE)=Upper('EN-US')  
LEFT JOIN GENCONSTANT GENC3 ON GENC3.CATEGORY='SALARYBANDTYPE' AND GENC3.CONSTANTVALUE=IM.SALARYBAND AND Upper(GENC3.LANGUAGECODE)=Upper('EN-US')  
LEFT JOIN GENCONSTANT GENC4 ON GENC4.CATEGORY='MEMYSENO' AND GENC4.CONSTANTVALUE=IM.ISCOMMISSION AND Upper(GENC4.LANGUAGECODE)=Upper('EN-US')  
LEFT JOIN GENCONSTANT GENC5 ON GENC5.CATEGORY='ENTITYTYPE' AND GENC5.CONSTANTVALUE=IM.ENTITYTYPE AND Upper(GENC5.LANGUAGECODE)=Upper('EN-US')  
LEFT JOIN GENCONSTANT GENC6 ON GENC6.CATEGORY='ENTITYID' AND GENC6.CONSTANTVALUE=IM.ENTITYID AND Upper(GENC6.LANGUAGECODE)=Upper('EN-US')  
ORDER BY IM.MEMBER_CODE DESC;


Member Dependancy Detail (Only View Purpose. No insert query) :

SELECT MEM.* FROM ( SELECT MEM.MEMBER_CODE MEMBERCODE,MEM.PARENT_ID MEMBER_CODE , MEM.MEMBER_ID,
( MEM.FIRST_NAME ||' '||MEM.LAST_NAME) MEMBERNAME,GRO.GROUP_NAME GROUPNAME,  CAT.CATEGORY_NAME CATEGORYNAME,
GEN1.CONSTANTNAME AS GENDERNAME,GEN2.CONSTANTNAME AS RELATIONNAME FROM IM_MEMBERS MEM  
LEFT JOIN IM_GROUPS GRO ON GRO.GROUP_CODE=MEM.GROUP_CODE  
LEFT JOIN IM_CATEGORIES CAT ON CAT.CATEGORY_CODE=MEM.CATEGORY_CODE  
LEFT JOIN GENCONSTANT GEN1 ON GEN1.CONSTANTVALUE=MEM.GENDER AND GEN1.CATEGORY='GENDER' AND Upper(GEN1.LANGUAGECODE)=Upper('EN-US') 
LEFT JOIN GENCONSTANT GEN2 ON GEN2.CONSTANTVALUE=MEM.RELATION  AND GEN2.CATEGORY='RELATIONS' AND Upper(GEN2.LANGUAGECODE)=Upper('EN-US')) MEM  
 