
Master :
SELECT IMRB.*,GEN.CONSTANTNAME STATUSNAME,GEN1.CONSTANTNAME AUTHORIZEDSTATUSNAME,  ADM.USERNAME USERNAME FROM 
IM_CLAIMBATCH IMRB  
JOIN (SELECT CONSTANTVALUE,CONSTANTNAME FROM GENCONSTANT WHERE CATEGORY='CALIMBATCHSTATUS' AND Upper(LANGUAGECODE)='EN-US')GEN 
ON GEN.CONSTANTVALUE=IMRB.STATUSCODE  
JOIN ADMUSER ADM ON ADM.USERCODE = IMRB.LASTMODIFIEDBY 
JOIN (SELECT CONSTANTVALUE,CONSTANTNAME FROM GENCONSTANT WHERE CATEGORY='AUTHORIZEDSTATUS' AND Upper(LANGUAGECODE)='EN-US')GEN1 
ON GEN1.CONSTANTVALUE=IMRB.AUTHORIZEDSTATUS AND IMRB.SOURCE = 2


Detail : 

SELECT ICMB.*,(IM.MEMBER_NAME)MEMBERNAME,IM.CARDNO MEMBERID,iM.POLICYNAME,IM.POLICYID,CUR.CURRENCYNAME FROM 
IM_CLAIMMEMBERBATCH ICMB   
JOIN IM_CLAIMMEMBERPOLICY_VW IM ON IM.MEMBERCODE = ICMB.MEMBERCODE AND IM.POLICYCODE = ICMB.POLICYCODE AND 
IM.CATEGORY_CODE = ICMB.CATEGORYCODE  
JOIN GENCURRENCY CUR ON CUR.CURRENCYCODE = ICMB.CURRENCY  WHERE ICMB.CLAIMBATCHCODE=100000000000044770

  



   
   
While saving the screen Source default value should be 2