SELECT JV.REFDATE,JV.REF_NO,JV.POLICYTYPE,JV.POLICYID,JV.POLICYNAME,JV.BILLINGTYPENAME,JV.BILLINGNAME,
JV.SOURCENAME,JV.MANAGEDBY,JV.PAYMENTTYPE,JV.INSTALLMENTDATE,JV.PAYMENTDATE,JV.AMOUNT,JV.RECEIVEDAMOUNT,
JV.BINCODE,JV.DOCUMENTTYPE,
'Report generated on '||To_Char(SYSDATE,'DD/MM/RRRR')||' and this does not include the installment due after '||
To_Char(:EDATE,'DD/MM/RRRR') REPORTHEADER,
(Nvl(AMOUNT,0)-Nvl(RECEIVEDAMOUNT,0)) OSAMOUNT FROM 
(SELECT  HDR.* FROM IM_FIN_OS_DETAIL_LIST HDR WHERE  HDR.POLICYID IS NOT NULL 
HDR.AGENTCODE = Nvl(:AGENTCODE,HDR.AGENTCODE) AND 
HDR.BROKERCODE = Nvl(:BROKERCODE,HDR.BROKERCODE) AND
HDR.GROUP_CODE = Nvl(:GROUPCODE,HDR.GROUPCODE)
HDR.REFDATE <= :EDATE AND HDR.INSTALLMENTDATE <= :EDATE) JV ORDER BY POLICYTYPE,POLICYNAME,REF_NO ASC


:AGENTCODE

SELECT AGENT_ID,AGENT_NAME_EN,AGENTCODE FROM IM_AGENTS


:BROKERCODE

SELECT BROKERCODE,BROKER_ID,BROKER_NAME_EN FROM IM_BROKERS

:GROUPCODE

SELECT GROUP_CODE,GROUP_NAME FROM IM_GROUPS