SELECT HDR.POLICYID,HDR.POLICYNAME,HDR.SOURCETYPE,HDR.SOURCENAME,HDR.INCEPTIONPREMIUM,
HDR.INCEPTIONPAIDAMOUNT,INCEPTIONOUTSTANDINGAMT,ADDITIONPREMIUM,ADDITIONPAIDAMOUNT,
ADDITIONOUTSTANDINGAMT,'Report generated on '||To_Char(SYSDATE,'DD/MM/RRRR')||' 
and this does not include the installment due after '||To_Char(EDATE,'DD/MM/RRRR') REPORTHEADER
FROM IM_FIN_OS_SUMMARY_LIST HDR WHERE  HDR.POLICYID IS NOT NULL AND
(LSTROPTION1='N' OR  nvl(HDR.BROKERCODE,0)=0 ) and (LSTROPTION2='N' OR (  nvl(HDR.AGENTCODE,0)=0)) and 
(LSTROPTION3='N' OR  (HDR.AGENTCODE is  null and HDR.BROKERCODE is  null))  AND
HDR.AGENTCODE = Nvl(:AGENTCODE,HDR.AGENTCODE) AND 
HDR.BROKERCODE = Nvl(:BROKERCODE,HDR.BROKERCODE) AND
HDR.GROUP_CODE = Nvl(:GROUPCODE,HDR.GROUPCODE);

:AGENTCODE

SELECT AGENT_ID,AGENT_NAME_EN,AGENTCODE FROM IM_AGENTS


:BROKERCODE

SELECT BROKERCODE,BROKER_ID,BROKER_NAME_EN FROM IM_BROKERS

:GROUPCODE

SELECT GROUP_CODE,GROUP_NAME FROM IM_GROUPS