SELECT PR.*,GEN.CONSTANTNAME RENEWALTYPENAME,GEN1.CONSTANTNAME AUTHORIZEDSTATUSNAME,NVL(POL.POLICYID,IMP.POLICYID) POLICYID, 
NVL(POL.POLICYNAME,IMP.POLICYNAME) POLICYNAME,  NVL(POL.STARTDATE,IMP.STARTDATE) STARTDATE, 
NVL(POL.ENDDATE,IMP.ENDDATE) ENDDATE,GEN2.CONSTANTNAME TYPENAME FROM IM_POLICY_RENEWAL PR    
LEFT JOIN IM_POLICY POL ON POL.POLICYCODE=DECODE(PR.TYPECODE,1,PR.POLICYCODE,0)   
JOIN ADMCOMPANY ADMCOM ON ADMCOM.COMPANYCODE=PR.COMPANYCODE AND ADMCOM.COMPANYCODE=1 
LEFT JOIN GENCONSTANT GEN ON GEN.CONSTANTVALUE=PR.RENEWALTYPE  AND GEN.CATEGORY='PERIODTYPE' AND GEN.LANGUAGECODE='en-US'  
LEFT JOIN GENCONSTANT GEN1 ON GEN1.CONSTANTVALUE=PR.AUTHORIZEDSTATUS  AND GEN1.CATEGORY='AUTHORIZEDSTATUS' 
AND GEN1.LANGUAGECODE='en-US'  
LEFT JOIN  GENCONSTANT GEN2 ON GEN2.CONSTANTVALUE=PR.TYPECODE AND GEN2.CATEGORY='MEMBERPOLICYTYPE' AND 
GEN2.LANGUAGECODE='en-US'  
LEFT JOIN IM_INDIVIDUALPOLICY IMP ON IMP.INDIVIDUALPOLICYCODE=DECODE(PR.TYPECODE,2,PR.POLICYCODE,0)   
ORDER  BY PR.POLICYRENWALCODE DESC;


CATEGORY DETAIL :

SELECT PCD.*,GC.CATEGORY_NAME CATEGORYNAME,PLA.PLAN_NAME PLANNAME FROM 
(SELECT POLCAT.PCDCODE CATEGORYDETCODE, POLCAT.POLICYCODE ,POLCAT.CATEGORYCODE,POLCAT.PLANCODE,
POLCAT.FRONTINGSETTING,POLCAT.ALTLIMIT, POLCAT.IPLIMIT, POLCAT.OPLIMIT,1 POLICYTYPE FROM IM_POLICY_CATEGORYDTL POLCAT 
UNION ALL  SELECT INDCAT.POLICYCATEGORYCODE CATEGORYDETCODE, INDCAT.INDIVIDUALPOLICYCODE AS  
POLICYCODE,INDCAT.CATEGORYCODE,INDCAT.PLANCODE,INDCAT.FRONTINGSETTING,INDCAT.ALTLIMIT, INDCAT.IPLIMIT, INDCAT.OPLIMIT,
2 POLICYTYPE FROM IM_NGIINDPOLICYCATEGORY INDCAT )PCD  
LEFT JOIN IM_CATEGORIES GC ON GC.CATEGORY_CODE=PCD.CATEGORYCODE  
LEFT JOIN IM_PLANS PLA ON PLA.PLAN_CODE=PCD.PLANCODE WHERE PCD.POLICYCODE=100000000000006225;