SELECT PMU.LOGCODE,PMU.SERIALNO,PMU.POLICYCODE,PMU.REFNO,PMU.REFDATE,POL.POLICYID,POL.POLICYNAME,PMU.UPLOADON,
GEN.CONSTANTNAME AS UPLOADTYPENAME,
EUT.UPLOADNAME,IMPORTEDRECORDCOUNT,UPLOADEDRECORDCOUNT FROM IM_POLICYMEM_UPLOAD PMU    
LEFT JOIN IM_POLICY POL ON POL.POLICYCODE=PMU.POLICYCODE     
LEFT JOIN IM_EXCEL_UPLOAD_TEMP_HDR EUT ON EUT.UPLOADCODE=PMU.UPLOADTEMPLATECODE    
LEFT JOIN GENCONSTANT GEN ON GEN.CONSTANTVALUE=PMU.UPLOADTYPE AND GEN.CATEGORY='UPLOADTYPE' AND LANGUAGECODE='en-US'  
