SELECT POL.GROUP_CODE,
POL.GROUP_NAME,
POL.POLICYNO,
POL.CLIENTNAME,
POL.GROSSPREMIUM,
POL.COMMISIONPREMKUM,
POL.NETPREMIUM,
POL.EARNPREMIUM,
POL.NETCLAIMPAID,
POL.PENDINGCLAIMPAID,
POL.TOTALCLAIMED,
POL.EFFECTIVEDATE,
POL.EXPIRYDATE,
POL.TOTALDAYS,
POL.EARNEDDAYS,
POL.EARNEDDAYSIBNRDAYS,
ROUND(POL.IBNRAMOUNT,2) ,
ROUND((NVL((POL.TOTALCLAIMED+POL.IBNRAMOUNT)/DECODE(NVL(EARNPREMIUM,0),0,1,EARNPREMIUM) ,0)*100),2) LOSSRATIO,
POL.REPORTPRINTDATE,
REPORTPRINTENDDATE,
POL.EMIRATENAME 
FROM (
SELECT
POL.GROUP_CODE,
POL.GROUP_NAME,
POL.POLICYNO,
POL.CLIENTNAME,
POL.GROSSPREMIUM,
POL.COMMISIONVALUE COMMISIONPREMKUM,  
POL.NETPREMIUM,
DECODE(POL.NETPREMIUM,0,0,ROUND(((POL.NETPREMIUM/DECODE(TOTALDAYS,0,1,TOTALDAYS))*EARNEDDAYS),2)) EARNPREMIUM,
NETCLAIMPAID,
PENDINGCLAIMPAID,
(NVL(NETCLAIMPAID,0)+NVL(PENDINGCLAIMPAID,0)) TOTALCLAIMED,
POL.EFFECTIVEDATE,
POL.EXPIRYDATE,
TOTALDAYS,
EARNEDDAYS,
EARNEDDAYSIBNRDAYS,
DECODE(SIGN(45-ROUND(:EDATE-EXPIRYDATE+1)),-1,0,
NVL(((NVL(NETCLAIMPAID,0)+NVL(PENDINGCLAIMPAID,0))/DECODE(NVL((EARNEDDAYS-EARNEDDAYSIBNRDAYS),0),0,1, EARNEDDAYS-EARNEDDAYSIBNRDAYS))*EARNEDDAYSIBNRDAYS ,0)) IBNRAMOUNT,
TO_DATE(:SDATE,'DD/MM/RRRR') REPORTPRINTDATE,
TO_DATE(:EDATE,'DD/MM/RRRR') REPORTPRINTENDDATE,
POL.EMIRATENAME 
FROM
(SELECT POL.*,
(NVL(POL.GROSSPREMIUM,0)-
ROUND(NVL((SELECT SUM(NVL(DECODE(CALC_METHOD,0,IM_IP_COMMISSION.DEFAULTVALUE,(IM_IP_COMMISSION.DEFAULTVALUE/100*POL.GROSSPREMIUM)),0)) FROM IM_IP_COMMISSION WHERE IM_IP_COMMISSION.INDIVIDUALPOLICYCODE=POL.POLICYCODE),0),2)
) NETPREMIUM,
ROUND(NVL((SELECT SUM(NVL(DECODE(CALC_METHOD,0,IM_IP_COMMISSION.DEFAULTVALUE,(IM_IP_COMMISSION.DEFAULTVALUE/100*POL.GROSSPREMIUM)),0)) FROM IM_IP_COMMISSION WHERE IM_IP_COMMISSION.INDIVIDUALPOLICYCODE=POL.POLICYCODE),0),2) COMMISIONVALUE
FROM
(
SELECT
GETEMIRATENAME(POL.INDIVIDUALPOLICYCODE) EMIRATENAME,
POL.INDIVIDUALPOLICYCODE POLICYCODE,
POL.POLICYID POLICYNO,
POL.POLICYNAME CLIENTNAME,
NVL(GET_POLICYFINALPREMIUM(2,POL.INDIVIDUALPOLICYCODE),0) GROSSPREMIUM, 
GRO.MEMBER_CODE  GROUP_CODE,
GRO.FIRST_NAME GROUP_NAME,
POL.STARTDATE EFFECTIVEDATE,
POL.ENDDATE EXPIRYDATE,
NVL(((POL.ENDDATE-POL.STARTDATE)),0)+1 TOTALDAYS,      
CASE WHEN TO_DATE(:EDATE,'DD/MM/RRRR')<TO_DATE(POL.ENDDATE,'DD/MM/RRRR') THEN
NVL(((TO_DATE(:EDATE,'DD/MM/RRRR')-TO_DATE(POL.STARTDATE,'DD/MM/RRRR') )),0) +1
ELSE
NVL(((TO_DATE(POL.ENDDATE,'DD/MM/RRRR')-TO_DATE(POL.STARTDATE,'DD/MM/RRRR') )),0) +1
END EARNEDDAYS,   
0 EARNEDDAYSIBNRDAYS,
NVL(GET_CLAIMPAYMENTAMT(2,POL.INDIVIDUALPOLICYCODE,'YYN',:SDATE,:EDATE,:UWYEAR),0) NETCLAIMPAID,
NVL(GET_PENDING_CLAIMPAYMENTAMT(2,POL.INDIVIDUALPOLICYCODE,'YYN',:SDATE,:EDATE,:UWYEAR),0) PENDINGCLAIMPAID,
POL.OWNERCODE
FROM (SELECT * FROM IM_INDIVIDUALPOLICY WHERE INDIVIDUALPOLICYCODE = Nvl(:P_INDIVIDUALPOLICYCODE,INDIVIDUALPOLICYCODE)
AND OWNERCODE = Nvl(:P_OWNERCODE,OWNERCODE)
)
POL
JOIN IM_MEMBERS GRO ON GRO.MEMBER_CODE=POL.MEMBERCODE  
) POL  
) POL   
)POL