Header :
SELECT HDR.* FROM IM_EDITPRIORREQUEST_VW HDR

Diagnosis :
SELECT DTL.*,GEN.CONSTANTNAME TYPENAME,IVD.CODE DIAGNOSISCODE,IVD.SHORTDESC FROM IM_AUTHORIZATION_PROCESS_DTL DTL  
LEFT JOIN IM_VERSION_DETALIS IVD ON IVD.DETAILCODE = DTL.VERSIONDETAILCODE  
LEFT JOIN GENCONSTANT GEN ON UPPER(GEN.CONSTANTNAME) = UPPER(DTL.TYPE) AND GEN.CATEGORY='IMDIAGNOSISTYPE' 
AND Upper(GEN.LANGUAGECODE) = 'EN-US' WHERE NVL(DTL.TYPE,0) <> 0 AND DTL.CLAIM_CODE=100000000000003613;

Activity :
SELECT DTL.*,ACTTYP.TYPENAME,  VERDET.CODE DRUGCODE,VERDET.SHORTDESC,IMVRDD.CODE RECOVERYREASON,IBC.BENEFIT_ID BENEFITID 
FROM IM_AUTHORIZATION_PROCESS_DTL DTL  
LEFT JOIN IM_ACTIVITY_TYPES ACTTYP ON ACTTYP.TYPECODE = DTL.ACTIVITY_CODE  
LEFT JOIN IM_BENEFIT_CODES IBC ON IBC.BENEFIT_CODE = DTL.BENEFIT_CODE  
LEFT JOIN IM_VERSION_DETALIS VERDET ON VERDET.DETAILCODE = DTL.VERSIONDETAILCODE  
LEFT JOIN IM_VERSION_DETALIS IMVRDD  ON (IMVRDD.DETAILCODE) = DTL.DENIAL_REASON 
WHERE NVL(DTL.TYPE,0) = 0  AND DTL.CLAIM_CODE=100000000000003613;

Observation Detail : 
SELECT IMPRO.* FROM (SELECT IMPRO.*,DECODE(IMPRO.OBSERVATION_TYPE,'FILE','',IMPRO.VALUE) OBSVALUE,
DTL.ACTIVITY_DETAIL_CODE FROM EPRIOR_OBSERVATIONS IMPRO  
LEFT JOIN IM_AUTHORIZATION_PROCESS_DTL DTL ON DTL.SYS_ACTIVITY_ID = IMPRO.SYS_ACTIVITY_ID 
WHERE DTL.ACTIVITY_CODE <> 100000000000000001) IMPRO WHERE IMPRO.ACTIVITY_DETAIL_CODE=100000000000013226;