SELECT TPC.*,GEN.CONSTANTNAME AS CPTNAME,GEN1.CONSTANTNAME AS FACTORTYPENAME, GEN3.CONSTANTNAME CALMETHODNAME  
FROM IM_TARIFF_PER_CATEGORY TPC  
JOIN ADMCOMPANY ADMCOM ON ADMCOM.COMPANYCODE=TPC.COMPANYCODE AND TPC.COMPANYCODE =1  
LEFT JOIN GENCONSTANT GEN3 ON  GEN3.CATEGORY= 'SLABCALCULATIONMODE' AND GEN3.LANGUAGECODE='EN-US' AND 
GEN3.CONSTANTVALUE=TPC.CALMETHODCODE  
LEFT JOIN GENCONSTANT GEN ON GEN.CONSTANTVALUE =TPC.CPTCODE AND GEN.CATEGORY='CPTMAIN' AND GEN.LANGUAGECODE='EN-US' 
LEFT JOIN GENCONSTANT GEN1 ON GEN1.CONSTANTVALUE =TPC.FACTORTYPECODE AND GEN1.CATEGORY='LBLFACTORBASE' AND 
GEN1.LANGUAGECODE='EN-US'  WHERE TPC.ASSIGN_CODE=1