 
DELETE FROM IM_CLAIM_RESUBACTIVITY_RPT;
COMMIT;
L_RULES:=IM_RESUBACTIVITY_RPT(P_PROVIDERCODE,P_SDATE,P_EDATE);    

SELECT CPH.INVOICENUMBER,CPH.CARDNO,IMP.AMEMBERNAME,IMP.APOLICYID,IMP.APOLICYNAME,
CPH.REQUEST_AMOUNT GROSS,CPH.ORGINALPATIENTSHARE PATIENTSHARE,(CPH.REQUEST_AMOUNT-CPH.ORGINALPATIENTSHARE) NET,
TO_CHAR(CPH.TRANSACTIONDATE,'DD/MM/RRRR')  INVOICEDATE,TO_CHAR(CPH.TRANSACTIONDATE,'DD/MM/RRRR')  TRANSACTIONDATE,
TO_CHAR(CPH.ENCOUNTER_START_DATE,'DD/MM/RRRR')  TREATMENTDATE,
CPH.ACR_FORM_NO,CPH.INVOICENUMBER,PRO.PROVIDERID,PRO.PROVIDERNAME,
IVD.CODE||'-'||SubStr(IVD.SHORTDESC,0,500) CPT,IMA.QTY,IMA.REJECTIONAMOUNT,
IMC.NAME CLINICIAN,IVDD.CODE||'-'||SubStr(IVDD.SHORTDESC,0,500) REJECTIONCODE,CPH.RESUBMISSION_COMMENTS
FROM IM_CLAIM_PROCESS_HEADER CPH
JOIN IM_PROVIDERS PRO ON PRO.PROVIDERCODE = CPH.PROVIDER_CODE
JOIN IM_MEMBERS_MAT_VW IMP ON IMP.MEMBERPOLICYCODE = CPH.MEMBERPOLICYCODE
JOIN IM_CLINICIANS IMC ON IMC.CDCODE = CPH.CDCODE
LEFT JOIN IM_CLAIM_RESUBACTIVITY_RPT IMA ON IMA.CLAIM_CODE = CPH.CLAIM_CODE
LEFT JOIN IM_VERSION_DETALIS IVD ON IVD.DETAILCODE = IMA.VERSIONDETAILCODE
LEFT JOIN IM_VERSION_DETALIS IVDD ON IVDD.DETAILCODE = IMA.DENIALCODE    
WHERE Nvl(IMA.TYPE,0) = 0 AND CPH.PROVIDER_CODE = Nvl(:PROVIDERCODE,CPH.PROVIDER_CODE)
AND  CPH.CLAIM_STATUS = 1  AND NVL(ISRESUBMISSION,0) = 1 AND RESUBMISSION_COMMENTS IS NOT NULL
AND  CPH.ENCOUNTER_START_DATE BETWEEN Nvl(:P_TSDATE,SYSDATE-1000) AND Nvl(:P_TEDATE,SYSDATE)
AND CPH.TRANSACTIONDATE BETWEEN Nvl(:P_SDATE,SYSDATE-1000) AND Nvl(:P_EDATE,SYSDATE)
AND CPH.LASTMODIFIEDON BETWEEN Nvl(:P_PDATE,SYSDATE-1000) AND Nvl(:P_PDATE,SYSDATE)
 


