
SELECT CPH.CLAIM_CODE,CPH.SERIALNO,CPH.REQUEST_TYPE,NVL (POL.POLICYID, IPOL.POLICYID) POLICYID,
NVL (POL.POLICYNAME, IPOL.POLICYNAME) POLICYNAME,CPH.POLICYTYPECODE,GENPOL.CONSTANTNAME SOURCE,
CPH.PROVIDER_CODE,PRO.PROVIDERID,PRO.PROVIDERNAME,CPH.TRANSACTIONDATE,CPH.REQUEST_TYPE,
GEN3.CONSTANTNAME CLAIMTYPE,CPH.ACR_FORM_NO,CPH.TREATMENT_TYPE,GEN5.CONSTANTNAME TREATMENTTYPENAME,
CPH.ENCOUNTER_START_DATE,CPH.ENCOUNTER_END_DATE,CPH.BATCHCODE,IMCB.FROMID BATCHNO, CPH.NETWORKTYPE,
NWT.CONSTANTNAME NETWORKTYPENAME,CPH.ADMINISTRATEDBY,ADMBY.CONSTANTNAME ADMINISTRATEDBYNAME,
CPH.INVOICENUMBER,CPH.REQUEST_AMOUNT,CPH.APPROVED_AMOUNT,CPH.DENAILVALUE,CPH.CLAIM_STATUS,GEN8.CONSTANTNAME STATUS,
CPH.DENIAL_REASON,IMVRDD.CODE DENIALREASON,CPH.AUTHORIZEDSTATUS,GEN.CONSTANTNAME AUTHORIZEDSTATUSNAME,
CPH.CREATEDON,CPH.CREATEDBY,CPH.LASTMODIFIEDON,CPH.LASTMODIFIEDBY,CPH.CPNO CLAIMID
FROM (SELECT * FROM IM_CLAIM_PROCESS_HEADER WHERE ISNEXTCARE = 1 AND NEXTCARECLAIMHDRCODE IS NULL
AND TPACLAIMHDRCODE IS NULL) CPH 
LEFT JOIN IM_POLICY POL ON POL.POLICYCODE = CPH.POLICYCODE AND CPH.POLICYTYPECODE = 1
LEFT JOIN IM_INDIVIDUALPOLICY IPOL ON IPOL.INDIVIDUALPOLICYCODE = CPH.POLICYCODE AND CPH.POLICYTYPECODE = 2 
LEFT JOIN GENCONSTANT GENPOL ON     GENPOL.CONSTANTVALUE = CPH.POLICYTYPECODE
AND GENPOL.CATEGORY = 'MEMBERPOLICYTYPE' AND UPPER(GENPOL.LANGUAGECODE) = 'EN-US'  
LEFT JOIN IM_PROVIDERS PRO ON PRO.PROVIDERCODE = CPH.PROVIDER_CODE       
LEFT JOIN GENCONSTANT GEN ON     GEN.CONSTANTVALUE = CPH.AUTHORIZEDSTATUS
AND GEN.CATEGORY = 'AUTHORIZEDSTATUS' AND UPPER(GEN.LANGUAGECODE) = 'EN-US'
LEFT JOIN GENCONSTANT GEN3 ON     GEN3.CONSTANTVALUE = CPH.REQUEST_TYPE
AND GEN3.CATEGORY = 'CLAIMPROSOURCETYPE' AND UPPER(GEN3.LANGUAGECODE) = 'EN-US'
LEFT JOIN GENCONSTANT GEN5 ON     GEN5.CONSTANTVALUE = CPH.TREATMENT_TYPE
AND GEN5.CATEGORY = 'APPLICABLE' AND UPPER(GEN5.LANGUAGECODE) = 'EN-US'
LEFT JOIN IM_CLAIMBATCH IMCB ON IMCB.CLAIMBATCHCODE = CPH.BATCHCODE 
LEFT JOIN (SELECT CONSTANTNAME, CONSTANTVALUE FROM GENCONSTANT WHERE CATEGORY = 'NETWORKTYPE'
AND UPPER(LANGUAGECODE) = 'EN-US') NWT ON NWT.CONSTANTVALUE = CPH.NETWORKTYPE
LEFT JOIN (SELECT CONSTANTNAME, CONSTANTVALUE FROM GENCONSTANT WHERE CATEGORY = 'NGIQUOTATIONTYPE'
AND UPPER(LANGUAGECODE) = 'EN-US')ADMBY ON ADMBY.CONSTANTVALUE = CPH.ADMINISTRATEDBY
LEFT JOIN GENCONSTANT GEN8 ON     GEN8.CONSTANTVALUE = CPH.CLAIM_STATUS
AND GEN8.CATEGORY = 'CLAIMREQSTATUS' AND UPPER(GEN8.LANGUAGECODE) = 'EN-US'   
LEFT JOIN IM_VERSION_DETALIS IMVRDD ON (IMVRDD.DETAILCODE) = CPH.DENIAL_REASON     
ORDER BY CPH.AUTHORIZEDSTATUS ASC
/

