SELECT HDR.*,GEN1.CONSTANTNAME AUTHORIZEDSTATUSNAME,GEN2.CONSTANTNAME CALCULATIONTYPENAME FROM IM_TREATY_HDR HDR 
LEFT JOIN GENCONSTANT GEN1 ON GEN1.CONSTANTVALUE=HDR.AUTHORIZEDSTATUS AND GEN1.CATEGORY='AUTHORIZEDSTATUS' AND 
GEN1.LANGUAGECODE='en-US'  
LEFT JOIN GENCONSTANT GEN2 ON GEN2.CONSTANTVALUE=HDR.CALCULATIONTYPE AND GEN1.CATEGORY='PREMIUMCALCTYPE' AND 
GEN1.LANGUAGECODE='en-US' 


SELECT DTL.*,ISU.INS_NAME REINSURANCENAME FROM IM_TREATY_DTL DTL   
LEFT JOIN IM_INSURER ISU ON ISU.INSCODE=DTL.INSURERCODE  WHERE DTL.TREATYHDRCODE=100000000000000021