

SELECT COUNT(*) NOOFCLAIMS,ADM.USERNAME,'' PROCESSEDON FROM IM_CLAIM_PROCESS_HEADER CPH
JOIN ADMUSER ADM ON ADM.USERCODE = CPH.LASTMODIFIEDBY
JOIN IM_PROVIDERS PRO ON PRO.PROVIDERCODE = CPH.PROVIDER_CODE
WHERE CPH.CLAIM_STATUS = 2 AND
CPH.LASTMODIFIEDBY = Nvl(:p_usercode,CPH.LASTMODIFIEDBY)    
AND CPH.LASTMODIFIEDON BETWEEN :SDATE AND (:EDATE + 1)
GROUP BY ADM.USERNAME
ORDER BY USERNAME,TO_CHAR(MAX(CPH.LASTMODIFIEDON)) ASC
