SELECT
GENCUR.CURRENCYNAME CURENCY ,
TO_CHAR(CPH.ENCOUNTER_START_DATE,'DD/MM/RRRR')  ADMISSIONDATE ,
DECODE(CPH.REQUEST_TYPE , 4,'THIRD PARTY',IMM.APOLICYID) POLICYNUMBER ,
DECODE(CPH.REQUEST_TYPE , 4,'THIRD PARTY',IMM.APOLICYNAME) POLICYNAME ,
SG.GROUP_NAME AS SUBGROUPNAME,
DECODE(CPH.REQUEST_TYPE , 4,'THIRD PARTY',PRO.PROVIDERNAME) PROVIDERNAME ,
GEN2.CONSTANTNAME PROVIDERTYPE ,
CPH.INVOICENUMBER INVOICEX,
NVL(IMM.A_STAFF_ID,'0') STAFFNUMBER ,
DECODE(CPH.REQUEST_TYPE , 4,'THIRD PARTY',IMM.AMEMBERNAME) PATIENTNAME ,
NVL(IMM.A_CARDID,CPH.CARDNO) CARDNUMBER ,GEN3.CONSTANTNAME STATUS,
(DECODE(CPH.CLAIM_STATUS,2,CPH.APPROVED_AMOUNT,CPH.REQUEST_AMOUNT) +
NVL((SELECT SUM(DENIEDAMOUNT) DENIEDAMOUNT FROM IM_CLAIM_PROCESS_DETAIL_DTL D WHERE   D.DENIEDFOR=2  AND D.ACTIVITY_DETAIL_CODE IN
 (SELECT ACTIVITY_DETAIL_CODE FROM IM_CLAIM_PROCESS_DETAIL DTL WHERE  DTL.CLAIM_CODE = CPH.CLAIM_CODE ) ),0) ) CLAIM_AMOUNT,
 PRO.PROVIDERID PROVIDER ,TO_CHAR(APPROVED_DATE,'DD/MM/RRRR') SETTLEDDATE ,TO_CHAR(NVL(CPH.LASTMODIFIEDON,CPH.CREATEDON),'DD/MM/RRRR')  PROCESSEDDATE ,
 TO_CHAR(APPROVED_DATE,'DD/MM/RRRR') POVALIDATIONDATE,GC.CATEGORY_NAME PRODUCTCLASS ,IMM.A_FIRST_NAME PRINCIPALFRISTNAME ,
IMM.A_LAST_NAME PRINCIPALFAMILYNAME , TO_CHAR(IMM.ADATE_OF_BIRTH,'DD/MM/RRRR') DOB ,GEN4.CONSTANTNAME NATIONALITY ,
GEN6.CONSTANTNAME DEPENDENCY ,
NVL(GEN7.CONSTANTNAME ,(SELECT  MAX(GEN.CONSTANTNAME) FROM GENCONSTANT  GEN  WHERE GEN.CATEGORY='GENDER' AND GEN.LANGUAGECODE='en-US'  AND GEN.CONSTANTVALUE IN (SELECT MEM.GENDER FROM IM_MEMBERS MEM WHERE MEM.MEMBER_CODE=CPH.MEMBER_CODE))) AS GENDER,
NVL(GEN8.CONSTANTNAME,(SELECT  MAX(GEN.CONSTANTNAME) FROM GENCONSTANT  GEN  WHERE GEN.CATEGORY='MARITAL_STATUS' AND GEN.LANGUAGECODE='en-US'  AND GEN.CONSTANTVALUE IN (SELECT MEM.MARITAL_STATUS FROM IM_MEMBERS MEM WHERE MEM.MEMBER_CODE=CPH.MEMBER_CODE))) MARITAL_STATUS,
TO_CHAR(IMM.MEMBERSTARTDATE,'DD/MM/RRRR') POLICYINCEPTIONDATE ,TO_CHAR(NVL(IMM.MEMBERENDDATE,IMM.POLICYENDDDATE),'DD/MM/RRRR') EXPIRYDATE,
TO_CHAR((CPH.ENCOUNTER_START_DATE),'DD/MM/RRRR') TREATEMENT_END_DATE,NVL(BEN.BENEFITNAME,'PRESCRIBED DRUGS/PHARMACY') BENEFITNAME,
NVL(BEN.BENEFITID,'OPDRG') BENEFITID,
(SELECT LISTAGG (IMVD.SHORTDESC, ',') WITHIN GROUP (ORDER BY IMVD.SHORTDESC) FROM IM_CLAIM_PROCESS_DETAIL DTL
LEFT JOIN IM_ACTIVITY_TYPES  ACTTYP ON ACTTYP.TYPECODE=DTL.ACTIVITY_CODE
JOIN IM_VERSION_DETALIS IMVD ON IMVD.DETAILCODE = DTL.VERSIONDETAILCODE
WHERE ACTTYP.VALUE = -1 AND DTL.CLAIM_CODE = CPH.CLAIM_CODE AND DTL.TYPE = 1 GROUP BY DTL.CLAIM_CODE ) ICDCODES,
  (SELECT ICD.GROUPNAME  FROM IM_CLAIM_PROCESS_DETAIL DTL
 LEFT JOIN IM_ACTIVITY_TYPES ACTTYP ON ACTTYP.TYPECODE = DTL.ACTIVITY_CODE JOIN IM_VERSION_DETALIS IMVD ON IMVD.DETAILCODE = DTL.VERSIONDETAILCODE
 JOIN IM_ICDGROUPING ICD ON ICD.CODE = IMVD.CODE
 WHERE ACTTYP.VALUE = -1 AND DTL.CLAIM_CODE = CPH.CLAIM_CODE AND ROWNUM < 2) DIAGNOSISGENERALIZED
FROM
(SELECT * FROM IM_CLAIM_PROCESS_HEADER) CPH
LEFT JOIN VW_IM_CLAIM_PROCESS_DETAIL_BEN BEN ON BEN.CLAIM_CODE=CPH.CLAIM_CODE
JOIN IM_MEMBERPOLICY IMM ON CPH.MEMBERPOLICYCODE = IMM.MEMBERPOLICYCODE
AND IMM.TYPEE = 1
LEFT JOIN  IM_GROUPS SG ON SG.GROUP_CODE=NVL(IMM.A_SUBGROUPCODE,0)
LEFT JOIN IM_PROVIDERS PRO ON PRO.PROVIDERCODE=CPH.PROVIDER_CODE
LEFT JOIN GENCONSTANT GEN2 ON GEN2.CATEGORY='PROVIDERTYPE' AND GEN2.CONSTANTVALUE=PRO.PROVIDERTYPE AND GEN2.LANGUAGECODE='en-US'
LEFT JOIN GENCONSTANT GEN ON GEN.CATEGORY='AUTHORIZEDSTATUS' AND GEN.LANGUAGECODE='en-US' AND GEN.CONSTANTVALUE=CPH.AUTHORIZEDSTATUS
LEFT JOIN GENCONSTANT GEN3 ON GEN3.CATEGORY='CLAIMREQSTATUS' AND GEN3.LANGUAGECODE='en-US' AND GEN3.CONSTANTVALUE=CPH.CLAIM_STATUS
LEFT JOIN GENCONSTANT GEN5 ON   GEN5.CATEGORY='CLAIMPROSOURCETYPE' AND GEN5.LANGUAGECODE='en-US'  AND GEN5.CONSTANTVALUE=CPH.REQUEST_TYPE
LEFT JOIN GENCONSTANT GEN4 ON   GEN4.CATEGORY='FND_NATIONALITY' AND GEN4.LANGUAGECODE='en-US'  AND GEN4.CONSTANTVALUE=IMM.A_NATIONALITY
LEFT JOIN GENCONSTANT GEN6 ON   GEN6.CATEGORY='RELATIONS' AND GEN6.LANGUAGECODE='en-US'  AND GEN6.CONSTANTVALUE=IMM.ARELATION
LEFT JOIN GENCONSTANT GEN7 ON   GEN7.CATEGORY='GENDER' AND GEN7.LANGUAGECODE='en-US'  AND GEN7.CONSTANTVALUE=IMM.AGENDER
LEFT JOIN GENCONSTANT GEN8 ON   GEN8.CATEGORY='MARITAL_STATUS' AND GEN8.LANGUAGECODE='en-US'  AND GEN8.CONSTANTVALUE=IMM.AMARITAL_STATUS
LEFT JOIN IM_CATEGORIES GC ON GC.CATEGORY_CODE=CPH.CATEGORY_CODE
LEFT JOIN GENCURRENCY GENCUR ON GENCUR.CURRENCYCODE = NVL(CPH.CURRENCYCODE,100000000000000001)
LEFT JOIN ADMUSER ADM ON ADM.USERCODE = CPH.LASTMODIFIEDBY
WHERE CPH.TRANSACTIONDATE BETWEEN :SDATE AND :EDATE
AND CPH.POLICYCODE = Nvl(:POLICYCODE,CPH.POLICYCODE)
AND CPH.CLAIM_CODE IN (SELECT MAX(CLAIM_CODE) FROM IM_CLAIM_PROCESS_HEADER  WHERE POLICYCODE = P_POLICYCODE GROUP BY
INVOICENUMBER,MEMBER_CODE,ENCOUNTER_START_DATE,ISRESUBMISSION HAVING COUNT(CLAIM_CODE) = 1) ;
