SELECT (SELECT CURRENCYNAME FROM GENCURRENCY
WHERE CURRENCYCODE IN
(SELECT Nvl(CURRENCYCODE,100000000000000001) FROM IM_CLAIM_PROCESs_HEADER  WHERE CLAIM_CODE = CPH.CLAIM_CODE))CURRENCYNAME,
CPH.ACR_FORM_NO,
TO_CHAR(CPH.OCCURRENCE)  ADMISSIONDATE ,
TO_CHAR(CPH.REPORTED_DATE)  TRANSACTIONDATE,IMM.APOLICYNAME POLICYNAME,IMM.APOLICYID POLICYNUMBER,
GEN2.CONSTANTNAME PROVIDERTYPE ,
DECODE(CPH.REQUEST_TYPE,4,'THIRD PARTY',PRO.PROVIDERNAME) PROVIDERNAME,
CPH.UNIQ_CLAIM_ID INVOICEX,NVL(IMM.A_STAFF_ID,'0') STAFFNUMBER ,
DECODE(CPH.REQUEST_TYPE , 4,'THIRD PARTY',IMM.AMEMBERNAME) PATIENTNAME,CPH.CARDNO,
CPH.NETAMOUNT CLAIM_AMOUNT,CPH.RECOVERYAMOUNT  DENIED,0 DISCOUNT,
NULL SETTLEDDATE ,TO_CHAR(CPH.PAY_DATE)  PROCESSEDDATE ,NULL POVALIDATIONDATE,
GC.CATEGORY_NAME PRODUCTCLASS ,
IMM.A_FIRST_NAME PRINCIPALFRISTNAME ,
IMM.A_LAST_NAME PRINCIPALFAMILYNAME,
TO_CHAR(IMM.ADATE_OF_BIRTH) DOB ,
GEN4.CONSTANTNAME NATIONALITY ,
GEN6.CONSTANTNAME DEPENDENCY ,
GEN7.CONSTANTNAME GENDER,
GEN8.CONSTANTNAME MARITAL_STATUS,
TO_cHAR(IMM.MEMBERSTARTDATE) POLICYINCEPTIONDATE ,
TO_CHAR(NVL(IMM.MEMBERENDDATE,IMM.POLICYENDDDATE)) EXPIRYDATE,
TO_CHAR(NVL(CPH.ENCOUNTER_END_DATE,CPH.OCCURRENCE)) TREATEMENT_END_DATE,
(SELECT Max(BENEFIT_NAME) FROM IM_BENEFIT_CODES
WHERE BENEFIT_CODE IN (SELECT Max(BENEFIT_CODE) FROM IM_CLAIM_PROCESS_DETAIL WHERE CLAIM_CODE = CPH.CLAIM_CODE )) BENEFITNAME,
(SELECT Max(BENEFIT_ID) FROM IM_BENEFIT_CODES
WHERE BENEFIT_CODE IN (SELECT Max(BENEFIT_CODE) FROM IM_CLAIM_PROCESS_DETAIL WHERE CLAIM_CODE = CPH.CLAIM_CODE )) BENEFITID,
(SELECT LISTAGG (IMVD.SHORTDESC, ',') WITHIN GROUP (ORDER BY IMVD.SHORTDESC) FROM IM_CLAIM_PROCESS_DETAIL DTL
LEFT JOIN IM_ACTIVITY_TYPES  ACTTYP ON ACTTYP.TYPECODE=DTL.ACTIVITY_CODE
JOIN IM_VERSION_DETALIS IMVD ON IMVD.DETAILCODE = DTL.VERSIONDETAILCODE
WHERE ACTTYP.VALUE = -1 AND DTL.CLAIM_CODE = CPH.CLAIM_CODE AND DTL.TYPE = 1 GROUP BY DTL.CLAIM_CODE ) ICDCODES,
'PROCESSED' STATUS,
GRP.GROUP_NAME AS SUBGROUPNAME
FROM IM_CLAIM_ACTUARY CPH
LEFT JOIN IM_PROVIDERS PRO ON PRO.PROVIDERCODE=CPH.PROVIDER_CODE
LEFT JOIN IM_MEMBERPOLICY IMM ON CPH.MEMBERPOLICYCODE = IMM.MEMBERPOLICYCODE
LEFT JOIN IM_GROUPS  GRP  ON GRP.GROUP_CODE=NVL(IMM.A_SUBGROUPCODE,IMM.GROUPCODE)
LEFT JOIN IM_CATEGORIES GC ON GC.CATEGORY_CODE=IMM.CATEGORYCODE
LEFT JOIN GENCONSTANT GEN2 ON CATEGORY='PROVIDERTYPE' AND GEN2.CONSTANTVALUE=PRO.PROVIDERTYPE AND
UPPER(GEN2.LANGUAGECODE)='EN-US'
LEFT JOIN GENCONSTANT GEN7 ON   GEN7.CATEGORY='GENDER' AND UPPER(GEN7.LANGUAGECODE)='EN-US'  AND
GEN7.CONSTANTVALUE=IMM.AGENDER
LEFT JOIN GENCONSTANT GEN8 ON   GEN8.CATEGORY='MARITAL_STATUS' AND UPPER(GEN8.LANGUAGECODE)='EN-US'  AND
GEN8.CONSTANTVALUE=IMM.AMARITAL_STATUS
LEFT JOIN GENCONSTANT GEN4 ON   GEN4.CATEGORY='FND_NATIONALITY' AND UPPER(GEN4.LANGUAGECODE)='EN-US'  AND
GEN4.CONSTANTVALUE=IMM.A_NATIONALITY
LEFT JOIN GENCONSTANT GEN6 ON   GEN6.CATEGORY='RELATIONS' AND UPPER(GEN6.LANGUAGECODE)='EN-US'  AND
GEN6.CONSTANTVALUE=IMM.ARELATION
WHERE CPH.OCCURRENCE BETWEEN :SDATE AND :EDATE
AND CPH.POLICYCODE = Nvl(:P_POLICYCODE,CPH.POLICYCODE) AND TYPEE = 1
UNION
SELECT (SELECT CURRENCYNAME FROM GENCURRENCY
WHERE CURRENCYCODE IN
(SELECT Nvl(CURRENCYCODE,100000000000000001) FROM IM_CLAIM_PROCESs_HEADER  WHERE CLAIM_CODE = CPH.CLAIM_CODE))CURRENCYNAME,
CPH.CLAIMNUMBER ACR_FORM_NO,
TO_CHAR(CPH.TRANSACTION_DATE)  ADMISSIONDATE ,
TO_CHAR(CPH.REPORTEDDATE)  TRANSACTIONDATE,IMM.APOLICYNAME POLICYNAME,CPH.POLICYID POLICYNUMBER,
CPH.PROVIDERTYPE ,
CPH.PROVIDERNAME PROVIDERNAME,
CPH.INVOICENUMBER INVOICEX,NVL(IMM.A_STAFF_ID,'0') STAFFNUMBER ,
IMM.AMEMBERNAME PATIENTNAME,CPH.BENEFICARYCARDNUMBER CARDNO,
CPH.APPROVEDAMOUNT CLAIM_AMOUNT,CPH.DECLINEDAMOUNT  DENIED,0 DISCOUNT,
NULL SETTLEDDATE ,TO_CHAR(CPH.TRANSACTION_DATE)  PROCESSEDDATE ,NULL POVALIDATIONDATE,
GC.CATEGORY_NAME PRODUCTCLASS ,
IMM.A_FIRST_NAME PRINCIPALFRISTNAME ,
IMM.A_LAST_NAME PRINCIPALFAMILYNAME,
TO_CHAR(IMM.ADATE_OF_BIRTH) DOB ,
GEN4.CONSTANTNAME NATIONALITY ,
GEN6.CONSTANTNAME DEPENDENCY ,
GEN7.CONSTANTNAME GENDER,
GEN8.CONSTANTNAME MARITAL_STATUS,
TO_cHAR(IMM.MEMBERSTARTDATE) POLICYINCEPTIONDATE ,
TO_CHAR(NVL(IMM.MEMBERENDDATE,IMM.POLICYENDDDATE)) EXPIRYDATE,
TO_CHAR(NVL(CPH.DISCHARGEDATE,CPH.TRANSACTION_DATE)) TREATEMENT_END_DATE,
(SELECT Max(BENEFIT_NAME) FROM IM_BENEFIT_CODES
WHERE BENEFIT_CODE IN (SELECT Max(BENEFIT_CODE) FROM IM_CLAIM_PROCESS_DETAIL WHERE CLAIM_CODE = CPH.CLAIM_CODE )) BENEFITNAME,
(SELECT Max(BENEFIT_ID) FROM IM_BENEFIT_CODES
WHERE BENEFIT_CODE IN (SELECT Max(BENEFIT_CODE) FROM IM_CLAIM_PROCESS_DETAIL WHERE CLAIM_CODE = CPH.CLAIM_CODE )) BENEFITID,
(SELECT LISTAGG (IMVD.SHORTDESC, ',') WITHIN GROUP (ORDER BY IMVD.SHORTDESC) FROM IM_CLAIM_PROCESS_DETAIL DTL
LEFT JOIN IM_ACTIVITY_TYPES  ACTTYP ON ACTTYP.TYPECODE=DTL.ACTIVITY_CODE
JOIN IM_VERSION_DETALIS IMVD ON IMVD.DETAILCODE = DTL.VERSIONDETAILCODE
WHERE ACTTYP.VALUE = -1 AND DTL.CLAIM_CODE = CPH.CLAIM_CODE AND DTL.TYPE = 1 GROUP BY DTL.CLAIM_CODE ) ICDCODES,
'PROCESSED' STATUS,
GRP.GROUP_NAME AS SUBGROUPNAME
FROM IM_CLAIMRPT_OSCLAIMS_HDR CPH
LEFT JOIN IM_MEMBERPOLICY IMM ON CPH.MEMBERPOLICYCODE = IMM.MEMBERPOLICYCODE
LEFT JOIN IM_GROUPS  GRP  ON GRP.GROUP_CODE=NVL(IMM.A_SUBGROUPCODE,IMM.GROUPCODE)
LEFT JOIN IM_CATEGORIES GC ON GC.CATEGORY_CODE=IMM.CATEGORYCODE
LEFT JOIN GENCONSTANT GEN7 ON   GEN7.CATEGORY='GENDER' AND UPPER(GEN7.LANGUAGECODE)='EN-US'  AND
GEN7.CONSTANTVALUE=IMM.AGENDER
LEFT JOIN GENCONSTANT GEN8 ON   GEN8.CATEGORY='MARITAL_STATUS' AND UPPER(GEN8.LANGUAGECODE)='EN-US'  AND
GEN8.CONSTANTVALUE=IMM.AMARITAL_STATUS
LEFT JOIN GENCONSTANT GEN4 ON   GEN4.CATEGORY='FND_NATIONALITY' AND UPPER(GEN4.LANGUAGECODE)='EN-US'  AND
GEN4.CONSTANTVALUE=IMM.A_NATIONALITY
LEFT JOIN GENCONSTANT GEN6 ON   GEN6.CATEGORY='RELATIONS' AND UPPER(GEN6.LANGUAGECODE)='EN-US'  AND
GEN6.CONSTANTVALUE=IMM.ARELATION
WHERE CPH.TRANSACTION_DATE BETWEEN :SDATE AND :EDATE
AND CPH.POLICYCODE = Nvl(:P_POLICYCODE,CPH.POLICYCODE) AND TYPEE = 1
